### ISSUE TITLE
Windows exe please

### ISSUE THREAD

**Issue by jakesonline** [slowmoVideo/slowmoVideo#100]
Please post Windows executable. 64 bit

**Comment by valgit** [comment]
@jakesonline you can find a win64 exe here : (http://www.mediafire.com/file/23tbebr8aqy1bxc/slomovideo_win64.7z), but it's not the latest one. Creating a win64 binary is complicated !

**Comment by jakesonline** [comment]
Thanks!

**Comment by victoralbenor** [comment]
Is there a link to Windows CLI version?
I am having trouble compiling.
Thanks

**Comment by valgit** [comment]
@victoralbenor I am not aware of somebody having already compile the CLI version for windows

**Comment by ulatekh** [comment]
#156 has a link to a more recent Windows build.
