### ISSUE TITLE
Download page not displaying correctly

### ISSUE THREAD

**Issue by scottlawsonbc** [slowmoVideo/slowmoVideo#101]
The [website download page](http://slowmovideo.granjow.net/download.php) is not displaying correctly on the Edge browser or the latest version of Chrome. My OS is Windows 10.

Edge browser:
![image](https://cloud.githubusercontent.com/assets/2927085/19170120/feebfe0e-8bcb-11e6-8cf7-ca291d98b939.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/2927085/19170208/5a78c25c-8bcc-11e6-85a0-cf0b6197dfbe.png)

**Comment by Granjow** [comment]
Thank you, fixed!
