### ISSUE TITLE
Debian compiling error

### ISSUE THREAD

**Issue by gree303** [slowmoVideo/slowmoVideo#116]
After installing all required  packages I receive the following error:
`Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/moc_work_flow.cxx.o
Reaping winning child 0x263b690 PID 3006 
Live child 0x263b690 (slowmoVideo/project/CMakeFiles/sVproj.dir/moc_work_flow.cxx.o) PID 3011 
Live child 0x2620590 (slowmoVideo/project/CMakeFiles/sVproj.dir/abstractFlowSource_sV.cpp.o) PID 3008 
Reaping winning child 0x263b690 PID 3011 
Removing child 0x263b690 PID 3011 from chain.
Released token for child 0x263b690 (slowmoVideo/project/CMakeFiles/sVproj.dir/moc_work_flow.cxx.o).
Live child 0x2620590 (slowmoVideo/project/CMakeFiles/sVproj.dir/abstractFlowSource_sV.cpp.o) PID 3008 
Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/build'.
 File 'slowmoVideo/project/CMakeFiles/sVproj.dir/build' does not exist.
  Considering target file 'slowmoVideo/project/libsVproj.a'.
   File 'slowmoVideo/project/libsVproj.a' does not exist.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/link.txt'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/link.txt' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/projectPreferences_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/projectPreferences_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/renderPreferences_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/renderPreferences_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/tag_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/tag_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/node_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/node_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/nodeList_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/nodeList_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/segment_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/segment_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/segmentList_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/segmentList_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/nodeHandle_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/nodeHandle_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/renderTask_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/renderTask_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/xmlProjectRW_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/xmlProjectRW_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/abstractFrameSource_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/abstractFrameSource_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/imagesFrameSource_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/imagesFrameSource_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/videoFrameSource_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/videoFrameSource_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/emptyFrameSource_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/emptyFrameSource_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/abstractRenderTarget_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/abstractRenderTarget_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/imagesRenderTarget_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/imagesRenderTarget_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/videoRenderTarget_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/videoRenderTarget_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/abstractFlowSource_sV.cpp.o'.
    Still updating file 'slowmoVideo/project/CMakeFiles/sVproj.dir/abstractFlowSource_sV.cpp.o'.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/flowSourceOpenCV_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/flowSourceOpenCV_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/flowSourceV3D_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/flowSourceV3D_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/interpolator_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/interpolator_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/shutterFunction_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/shutterFunction_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/shutterFunctionList_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/shutterFunctionList_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/motionBlur_sV.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/motionBlur_sV.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/exportVideoRenderTarget.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/exportVideoRenderTarget.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/work_flow.cpp.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/work_flow.cpp.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_project_sV.cxx.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_project_sV.cxx.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_renderTask_sV.cxx.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_renderTask_sV.cxx.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_abstractFrameSource_sV.cxx.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_abstractFrameSource_sV.cxx.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_imagesFrameSource_sV.cxx.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_imagesFrameSource_sV.cxx.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_videoFrameSource_sV.cxx.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_videoFrameSource_sV.cxx.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_emptyFrameSource_sV.cxx.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_emptyFrameSource_sV.cxx.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_work_flow.cxx.o'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/moc_work_flow.cxx.o' was considered already.
    Considering target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/build.make'.
    File 'slowmoVideo/project/CMakeFiles/sVproj.dir/build.make' was considered already.
   Finished prerequisites of target file 'slowmoVideo/project/libsVproj.a'.
  The prerequisites of 'slowmoVideo/project/libsVproj.a' are being made.
 Finished prerequisites of target file 'slowmoVideo/project/CMakeFiles/sVproj.dir/build'.
The prerequisites of 'slowmoVideo/project/CMakeFiles/sVproj.dir/build' are being made.
Live child 0x2620590 (slowmoVideo/project/CMakeFiles/sVproj.dir/abstractFlowSource_sV.cpp.o) PID 3008 
/home/cb/Downloads/slowmoVideo/src/slowmoVideo/project/abstractFlowSource_sV.cpp: In member function ‘void AbstractFlowSource_sV::cleardirectory(QDir)’:
/home/cb/Downloads/slowmoVideo/src/slowmoVideo/project/abstractFlowSource_sV.cpp:40:16: error: ‘class QDir’ has no member named ‘removeRecursively’
         subDir.removeRecursively();
                ^
Reaping losing child 0x2620590 PID 3008 
slowmoVideo/project/CMakeFiles/sVproj.dir/build.make:503: recipe for target 'slowmoVideo/project/CMakeFiles/sVproj.dir/abstractFlowSource_sV.cpp.o' failed
make[2]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/abstractFlowSource_sV.cpp.o] Error 1
Removing child 0x2620590 PID 3008 from chain.
Reaping losing child 0x23831a0 PID 2992 
CMakeFiles/Makefile2:361: recipe for target 'slowmoVideo/project/CMakeFiles/sVproj.dir/all' failed
make[1]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/all] Error 2
Removing child 0x23831a0 PID 2992 from chain.
Reaping losing child 0x1b29b00 PID 2916 
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
Removing child 0x1b29b00 PID 2916 from chain.`

System: Debian 8 / Bunsenlabs

Can you see what I'm missing here? Thanks.

**Comment by valgit** [comment]
@gree303 can you paste your cmake log file ? and your QT version ?

**Comment by mbardeen** [comment]
Install the QT5 dependencies mentioned in the install guide.
