### ISSUE TITLE
Ignore identic frames

### ISSUE THREAD

**Issue by m93a** [slowmoVideo/slowmoVideo#119]
Some programs (eg. Movie Maker) can't deal with the optical flow so when you slow a video down, instead of computing the missing frames they just repeat one frame many times. It would be awesome if Slomo Video recognized those identic frames and acted as if they weren't there at all. This would mean I could edit the speed of the video in Movie Maker (it has simple preview, supports music etc.) and then let Slomo Video do the work.

Nevertheless you've done a great job! What a fantastic program!

**Comment by ulatekh** [comment]
Although it'd be a bit laborious, I think you could do this with discontinuous references to input frames. Across each duplicated frame, you'd have a node with the same x-coordinate (i.e. output frame), but y-coordinates (i.e. input frames) that skip the duplicated frame.

**Comment by Granjow** [comment]
> It would be awesome if Slomo Video recognized those identic frames

which is probably impossible because there is no way of knowing if frames are really identical or not (usually there are still small numerical differences due to the encoding) and we are again generating optical flow for nothing :)

I like the idea, but cannot see it in reality.

**Comment by m93a** [comment]
Ok, thank you for your comments, now I see why it's not feasible to implement. I'll close this issue then?

**Comment by Granjow** [comment]
Yes. I think what is actually needed is a nice way of integrating slowmoVideo into video editing applications and consider audio as well.

**Comment by ulatekh** [comment]
Have you tried ffmpeg's [mpdecimate](https://stackoverflow.com/questions/37088517/) filter?
