### ISSUE TITLE
GPU support (flowBuilder) - how?

### ISSUE THREAD

**Issue by Vylaern** [slowmoVideo/slowmoVideo#120]
Hi,

I was using for many times slowmo for Gentoo, and now a git version to compile.

How could I use flowBuilder (as in preferences is now greyed)? Should I compile it separatley? If yes, how? I use nvida card.

**Comment by valgit** [comment]
@Vylaern normaly flowbuilder is build as part of the slowmovideo build. So dit you check the build was Ok ?

**Comment by metal3d** [comment]
In my case, now flowBuilder executable found...
