### ISSUE TITLE
Request: Manual set final frame number

### ISSUE THREAD

**Issue by tetris-11** [slowmoVideo/slowmoVideo#121]
I've noticed that quicktime h264 encoded videos import strangely, where all frames are loaded in to the slowmoUI canvas, but the final frame is too low (less than the number of actual frames). 

(ffmpeg encoded h264 videos load fine though)

I'm sure correctly detecting the max number of frames is non-trivial, but I was wondering if you could add an option in Project -> Preferences to manually set the final frame number (or some kind of dragging feature)?

**Comment by valgit** [comment]
hi @tetris-11 , I remember that  there as an "of by one" error in framing counting corrected in last commit. What was your version you use ?

**Comment by tetris-11** [comment]
I was using v0.5-117-g5abd933

The problem seems to only persist in QuickTime .mov files over a certain time limit (>5 mins) from the same video source. If I convert them with ffmpeg they seem to detect fine, so it's probably just bad headers on my side.

I can upload a video if you want to play around (~200M), but I'm happy to close this otherwise

**Comment by valgit** [comment]
well, so, @tetris-11 I keep the information just in case ! thank you
