### ISSUE TITLE
Compile error 2017-02-27

### ISSUE THREAD

**Issue by evertvorster** [slowmoVideo/slowmoVideo#123]
Hi there. 
I am the maintainer for the slowmovideo-git package in Arch. 
It was recently reported that the package does not build anymore. 

I tried to build it myself and I get this error:
--------------snip--------------
[ 30%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/xmlProjectRW_sV.cpp.o
/var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.cpp: In static member function ‘static void XmlProjectRW_sV::loadFrameSource(QXmlStreamReader*, Project_sV*)’:
/var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.cpp:279:44: error: call of overloaded ‘compare(const char [10])’ is ambiguous
     if (frameSourceType.compare("videoFile") == 0) {
                                            ^
In file included from /usr/include/qt/QtCore/qregexp.h:47:0,
                 from /usr/include/qt/QtCore/qstringlist.h:47,
                 from /usr/include/qt/QtCore/qlist.h:1093,
                 from /usr/include/qt/QtCore/qhash.h:46,
                 from /usr/include/qt/QtCore/qdebug.h:45,
                 from /usr/include/qt/QtCore/QDebug:1,
                 from /var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/../lib/defs_sV.hpp:22,
                 from /var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.h:14,
                 from /var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.cpp:11:
/usr/include/qt/QtCore/qstring.h:1584:12: note: candidate: int QStringRef::compare(const QString&, Qt::CaseSensitivity) const
 inline int QStringRef::compare(const QString &s, Qt::CaseSensitivity cs) const Q_DECL_NOTHROW
            ^~~~~~~~~~
/usr/include/qt/QtCore/qstring.h:1515:9: note: candidate: int QStringRef::compare(const QByteArray&, Qt::CaseSensitivity) const
     int compare(const QByteArray &s, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
         ^~~~~~~
/var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.cpp:290:48: error: call of overloaded ‘compare(const char [7])’ is ambiguous
     } else if (frameSourceType.compare("images") == 0) {
                                                ^
In file included from /usr/include/qt/QtCore/qregexp.h:47:0,
                 from /usr/include/qt/QtCore/qstringlist.h:47,
                 from /usr/include/qt/QtCore/qlist.h:1093,
                 from /usr/include/qt/QtCore/qhash.h:46,
                 from /usr/include/qt/QtCore/qdebug.h:45,
                 from /usr/include/qt/QtCore/QDebug:1,
                 from /var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/../lib/defs_sV.hpp:22,
                 from /var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.h:14,
                 from /var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.cpp:11:
/usr/include/qt/QtCore/qstring.h:1584:12: note: candidate: int QStringRef::compare(const QString&, Qt::CaseSensitivity) const
 inline int QStringRef::compare(const QString &s, Qt::CaseSensitivity cs) const Q_DECL_NOTHROW
            ^~~~~~~~~~
/usr/include/qt/QtCore/qstring.h:1515:9: note: candidate: int QStringRef::compare(const QByteArray&, Qt::CaseSensitivity) const
     int compare(const QByteArray &s, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
         ^~~~~~~
/var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.cpp:306:47: error: call of overloaded ‘compare(const char [6])’ is ambiguous
     } else if (frameSourceType.compare("empty") == 0) {
                                               ^
In file included from /usr/include/qt/QtCore/qregexp.h:47:0,
                 from /usr/include/qt/QtCore/qstringlist.h:47,
                 from /usr/include/qt/QtCore/qlist.h:1093,
                 from /usr/include/qt/QtCore/qhash.h:46,
                 from /usr/include/qt/QtCore/qdebug.h:45,
                 from /usr/include/qt/QtCore/QDebug:1,
                 from /var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/../lib/defs_sV.hpp:22,
                 from /var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.h:14,
                 from /var/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/xmlProjectRW_sV.cpp:11:
/usr/include/qt/QtCore/qstring.h:1584:12: note: candidate: int QStringRef::compare(const QString&, Qt::CaseSensitivity) const
 inline int QStringRef::compare(const QString &s, Qt::CaseSensitivity cs) const Q_DECL_NOTHROW
            ^~~~~~~~~~
/usr/include/qt/QtCore/qstring.h:1515:9: note: candidate: int QStringRef::compare(const QByteArray&, Qt::CaseSensitivity) const
     int compare(const QByteArray &s, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
         ^~~~~~~
make[2]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/build.make:331: slowmoVideo/project/CMakeFiles/sVproj.dir/xmlProjectRW_sV.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:392: slowmoVideo/project/CMakeFiles/sVproj.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
==> ERROR: A failure occurred in build().
-------------snip--------------------

Kind regards,
Evert

**Comment by evertvorster** [comment]
I did a bit of searching... could this be related?

http://stackoverflow.com/questions/4672152/call-of-overloaded-function-is-ambiguous/4673320

**Comment by valgit** [comment]
@evertvorster : I don't know what's going on since this part of code hasn't change since age ;-) what is your compiler version ? QT version ?

**Comment by evertvorster** [comment]
I have qt at version 5.8.0-5 and gcc at version 6.3.1-1
I don't know either, and I have not recompiled your software on my system in a long time.

**Comment by valgit** [comment]
@evertvorster from what I see looking around, the problem came from GCC 6.x !
quoting some other people :
> It is not a question of support, the new versions of gcc are usually more sensitive to such things and give warnings that are not in previous version.

but I don't know if there are ways to tell GCC to be less sensitive !

**Comment by evertvorster** [comment]
Hi there. 

From what I can tell this is a bug. I have seen other software with the same compiler bug, and they fixed it because at some point everyone will be compiling with gcc 6. From the link I put into one of my earlier comments, it would appear that it is a matter of telling the compiler which variation of "0" you want, and then the error is fixed.

**Comment by valgit** [comment]
@evertvorster can you check my latest pull ?

**Comment by evertvorster** [comment]
Hi there. 
I see no change on the error message. Thanks for trying, though.

**Comment by evertvorster** [comment]
Hi there. 
I don't see any changes to master branch since Dec 2016. With a little more investigation I see that the fix you propose is only a pull request, so it did not apply to my copy of the git. 

Where can I find some help on how to merge a pull request on my local copy of the source base?

Also, your fix may still work, apparently I never tried it... :)

**Comment by evertvorster** [comment]
Aha. I finally got your changes merged in.... it took a few minutes to figure out how you organized your source. 
I checked out your version of slowmovideo from github, and the correct branch. 
Finally I am able to compile slowmovideo on my system. 
You should be OK to merge this change into the master on the slowmovideo git repo.

Kind regards,
Evert

**Comment by valgit** [comment]
thanks @evertvorster

**Comment by valgit** [comment]
patch #124 has been merge in master resolving this issue.
