### ISSUE TITLE
Very slow downloads for windows executables on website

### ISSUE THREAD

**Issue by Atemu** [slowmoVideo/slowmoVideo#128]
It downloads at about 65KB/s which is unacceptable for a 30-90MB file.

It's not throttling on my end, the speedtest says that my full bandwidth can be used (~4.8MB/s).

http://slowmovideo.granjow.net/download.php     
http://slowmovideo.granjow.net/builds/slowmoVideo_0.3.1+d356d79_win32.7z

**Comment by Granjow** [comment]
@Atemu Thanks for the report. I am looking into it – first thought it was my connection only, but if you observe the same, it is not.
