### ISSUE TITLE
Trying to create new RPM - libV3D dependency

### ISSUE THREAD

**Issue by metal3d** [slowmoVideo/slowmoVideo#139]
Hi,
I created a new specfile to build RPM on fedora 26 (fedora 25 won't work) and the build is ok (rpmplint is ok too). I do this package to build git HEAD and to be able to provide this to rpmfusion.  

The problem appears when I want to install the package:

```
$ sudo dnf install /home/pafer/rpmbuild/RPMS/x86_64/slowmoVideo-git33f5c84-1.fc26.x86_64.rpm
Error: 
 Problem: conflicting requests
  - nothing provides libV3D.so()(64bit) needed by slowmoVideo-git33f5c84-1.fc26.x86_64
```

When rpm is built, I actually find that dependency:

```
# I truncated the output to show you the dependency
Requires: /usr/bin/env ... libV3D.so()(64bit)
```

I tried to find if any of binaries are linked to libV3D.so but there are none. So, what is the problem ? Why that library that is not build anymore (as said in documentation) is found as dependency ?

Thanks

**Comment by metal3d** [comment]
see #140 that resolves that problem

**Comment by valgit** [comment]
thanks @metal3d I merge your request but uno why there is this dependency

**Comment by metal3d** [comment]
rpm build is very complete and checks different kinds of compilation. If it find a cmake build, so it will resolve what is configured inside.
Because your configuration didn't say that libv3D is "static", so rpmbuild find that the binary will need a dynamic library.
That's very efficient to not forget something, and to be sure that the build is not broken. That was the case ;)
