### ISSUE TITLE
libavcodec53 dependencies are unsatisfiable

### ISSUE THREAD

**Issue by unfa** [slowmoVideo/slowmoVideo#144]
Hey!
I recently learned about slomwoVideo, and I wanted to give it a try.

I have downloaded and attempted to install this file:
http://slowmovideo.granjow.net/builds/slowmoVideo_0.2.4-1_ubuntu11.10_i386.deb

But it failed to resolve dependencies:
![image](https://user-images.githubusercontent.com/491704/32797306-ab91d3ac-c971-11e7-8cd7-12113048ba9c.png)

It seems that this program have not seen any development since 2013 - is it possible to install and run this program in 2017 without using an old Ubuntu distribution?

**Comment by valgit** [comment]
@unfa you should upload and/or build a more recent version. The one you use is deprecated.

**Comment by Granjow** [comment]
This should be fixed with the current AppImage release.
