### ISSUE TITLE
Where is slowmoUI.exe ?

### ISSUE THREAD

**Issue by jmevel** [slowmoVideo/slowmoVideo#153]
Hello, I just want to download slowmoVideo for windows but I can't find any link for that.

The download page says "For Windows you additionally need to download ffmpeg from Zeranoe (32-bit Builds (Static)) and extract ffmpeg.exe into the same directory as slowmoUI.exe."

And that's pretty much it. I have no idea where to find this slowmoUI.exe file. I don't want to compile the project myself, I just want to use it.

All I can find on google are unofficial links. So where is the official link?

Thank you

**Comment by valgit** [comment]
Hi @jmevel , there is no official windows binaries, but from the [g+ community]((https://plus.google.com/communities/116570263544012246711) you can find a working windows binaries here : [win64 binaries](http://www.mediafire.com/file/23tbebr8aqy1bxc/slomovideo_win64.7z)
