### ISSUE TITLE
compiling fails

### ISSUE THREAD

**Issue by treborxy** [slowmoVideo/slowmoVideo#183]
Hello,
when trying to compile the latest source (as from 2020-04-14)  I get an error saying "recipe for target 'src/lib/CMakeFiles/sVencode.dir/ffmpeg_writer.cpp.o' failed". Could you please give me a hint what I'm doing wrong?

Output is as follows:

`
robert@Reaktor:~/github/slowmoVideo/build$ make
Scanning dependencies of target sVflow_autogen
[  1%] Automatic MOC, UIC and RCC for target sVflow
[  1%] Built target sVflow_autogen
Scanning dependencies of target sVflow
[  1%] Building CXX object src/lib/libsvflow/CMakeFiles/sVflow.dir/src/flowRW_sV.cpp.o
[  2%] Building CXX object src/lib/libsvflow/CMakeFiles/sVflow.dir/src/flowField_sV.cpp.o
[  3%] Building CXX object src/lib/libsvflow/CMakeFiles/sVflow.dir/sVflow_autogen/mocs_compilation.cpp.o
[  4%] Linking CXX static library libsVflow.a
[  4%] Built target sVflow
Scanning dependencies of target sVencode_autogen
[  5%] Automatic MOC, UIC and RCC for target sVencode
[  5%] Built target sVencode_autogen
Scanning dependencies of target sVencode
[  5%] Building CXX object src/lib/CMakeFiles/sVencode.dir/ffmpeg_writer.cpp.o
/home/robert/github/slowmoVideo/src/lib/ffmpeg_writer.cpp:70:0: warning: ignoring #pragma mark  [-Wunknown-pragmas]
 #pragma mark -
 
/home/robert/github/slowmoVideo/src/lib/ffmpeg_writer.cpp:133:0: warning: ignoring #pragma mark  [-Wunknown-pragmas]
 #pragma mark -
 
/home/robert/github/slowmoVideo/src/lib/ffmpeg_writer.cpp:134:0: warning: ignoring #pragma mark C [-Wunknown-pragmas]
 #pragma mark C bridge
 
In file included from /home/robert/github/slowmoVideo/src/lib/defs_sV.hpp:29:0,
                 from /home/robert/github/slowmoVideo/src/lib/ffmpeg_writer.cpp:14:
/home/robert/github/slowmoVideo/build/version.h:9:35: error: ‘v0’ was not declared in this scope
 #define SLOWMOVIDEO_VERSION_PATCH v0.6
                                   ^
/home/robert/github/slowmoVideo/src/lib/defs_sV.hpp:39:24: note: in expansion of macro ‘SLOWMOVIDEO_VERSION_PATCH’
     static int micro = SLOWMOVIDEO_VERSION_PATCH;
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/robert/github/slowmoVideo/build/version.h:9:35: note: suggested alternative: ‘y0’
 #define SLOWMOVIDEO_VERSION_PATCH v0.6
                                   ^
/home/robert/github/slowmoVideo/src/lib/defs_sV.hpp:39:24: note: in expansion of macro ‘SLOWMOVIDEO_VERSION_PATCH’
     static int micro = SLOWMOVIDEO_VERSION_PATCH;
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
src/lib/CMakeFiles/sVencode.dir/build.make:62: recipe for target 'src/lib/CMakeFiles/sVencode.dir/ffmpeg_writer.cpp.o' failed
make[2]: *** [src/lib/CMakeFiles/sVencode.dir/ffmpeg_writer.cpp.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'src/lib/CMakeFiles/sVencode.dir/all' failed
make[1]: *** [src/lib/CMakeFiles/sVencode.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by Granjow** [comment]
@treborxy Yes, after adding the version tag, CMake failed. Fixed!

**Comment by treborxy** [comment]
Hello Granjow,
Thanks for that! 'make' now runs without error.
But then? (Sorry for being a beginner and stealing your time)
Maybe you could append the line
`sudo make install` ...

**Comment by Granjow** [comment]
You can run `src/slowmoUI/slowmoUI`.

This will become a bit clearer with #181.
