### ISSUE TITLE
symbol lookup error on Ubuntu 22.04

### ISSUE THREAD

**Issue by PanderMusubi** [slowmoVideo/slowmoVideo#202]
On Unbuntu 22.04 the following error occurs for version 0.6

    ./slowmoUI-0.6-x86_64.AppImage: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full

**Comment by jhite1234** [comment]
I have the same issue on 22.04. 
$ ./slowmoUI-0.6-x86_64.AppImage 
slowmoUI-0.6-x86_64.AppImage: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full

**Comment by Granjow** [comment]
Fixed in https://github.com/slowmoVideo/slowmoVideo/releases/tag/v0.6.1, thanks for reporting!

**Comment by PanderMusubi** [comment]
@Granjow can you also update the release in flatpak to 0.6.1? Thanks
