### ISSUE TITLE
SlmV & Ubuntu 14.10 compilation succeed but

### ISSUE THREAD

**Issue by dim162** [slowmoVideo/slowmoVideo#24]
SlmV & Ubuntu 14.10 studio compilation succeeded but when i launch the smUI, i don't have the gpu,v3d flow method & when i choose the smFlowBuilder... it don't keep it. 
I use the ppa:djcj/vlc-stable & opencl is working (i use & compile darktable, blender).

**Comment by valgit** [comment]
Hi, can you verify that you have the flowBuilder binary ? the compilation need to have glut and  glew to succeed and a little bit old X11 openGL ;-). It does not use OpenCL at all. 
maybe post your logs ?

**Comment by dim162** [comment]
Of course! the flowBuilder binary exist & it is not empty.
The compilation logs:  

dim@desktop:~/Desktop/slowmoVideo/build$ cmake ../src
-- checking: avformat.h
--           /usr/include/libavformat
-- checking: avcodec.h
--           /usr/include/libavcodec
-- checking: avutil.h
--           /usr/include/libavutil
-- checking: swscale.h
--           /usr/include/libswscale
-- FFMPEG libraries are at /usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswscale.so
-- CXX flags:  -Wall -O2
-- Additional libraries: 

======================V3D============================
* (info) Installation prefix: /usr/local.
         (Can be adjusted with -DCMAKE_INSTALL_PREFIX=your_path.  Default: .)
* (info) Shaders will be included in the binary: YES
         (Can be disabled with the cmake flag -DDISABLE_INCLUDE_SOURCE)
* (ok) OpenGL found in /usr/include: /usr/lib/x86_64-linux-gnu/libGLU.so;/usr/lib/x86_64-linux-gnu/libGL.so;/usr/lib/x86_64-linux-gnu/libSM.so;/usr/lib/x86_64-linux-gnu/libICE.so;/usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
* (ok) GLUT found in /usr/include: /usr/lib/x86_64-linux-gnu/libglut.so;/usr/lib/x86_64-linux-gnu/libXmu.so;/usr/lib/x86_64-linux-gnu/libXi.so
* (ok) GLEW found at /usr/include/GL
* (ok) JPEG libraries found at /usr/include: /usr/lib/x86_64-linux-gnu/libjpeg.so
* (ok) PNG libraries found at /usr/include;/usr/include
* V3D will be built:                        ---YES---
==================slowmoVideo========================
* (info) slowmoVideo installation goes to /usr/local.
         (Can be adjusted with -DCMAKE_INSTALL_PREFIX=your_path. Default is .)
* (ok) ffmpeg found at 
* (ok) OpenCV 2.4.9 found at .
* slowmoVideo will be built:                ---YES---
=======================END===========================

-- Configuring done
-- Generating done
-- Build files have been written to: /home/dim/Desktop/slowmoVideo/build
dim@desktop:~/Desktop/slowmoVideo/build$ 



& the log when i run smUI: 

dim@desktop:~/Desktop/slowmoVideo/build$ sudo slowmoUI
[sudo] password for dim: 
("slowmoUI") 
Adding  "Input monitor"  to the menu's widget list 
Adding  "Curve monitor"  to the menu's widget list 
Adding  "Render preview"  to the menu's widget list 
Adding unique key  "h" 
Adding unique key  "q" 
Adding unique key  "n" 
Adding unique key  "o" 
Adding unique key  "s" 
Adding unique key  "a" 
Adding unique key  "d" 
Adding unique key  "t" 
Adding unique key  "m" 
Checking  ""  ... 
Checking  "/usr/local/bin/slowmoFlowBuilder"  ... 
Invalid output from flow executable:  "" 
Checking  "/home/dim/Desktop/slowmoVideo/build/slowmoFlowBuilder"  ... 
Checking  "/usr/local/bin/slowmoFlowBuilder"  ... 
Invalid output from flow executable:  "" 
Checking  "/usr/bin/slowmoFlowBuilder"  ... 
Checking  "/usr/local/bin/slowmoFlowBuilder"  ... 
Invalid output from flow executable:  "" 
Checking  ""  ... 
QFileInfo::absolutePath: Constructed with empty filename
Checking  "/usr/local/bin/slowmoFlowBuilder"  ... 
Invalid output from flow executable:  "" 
Checking  "/usr/local/bin/slowmoFlowBuilder"  ... 
Invalid output from flow executable:  "" 
Checking  "/usr/local/bin/slowmoFlowBuilder"  ... 
Invalid output from flow executable:  ""

**Comment by valgit** [comment]
from what I see, it seem there is a problem with the program output, can you check : 
* where is your slowmoFlowBuilder
* output of slowmoFlowBuilder -v ?

**Comment by dim162** [comment]
In /usr/local/bin/. 

slowmoFlowBuilder -v:
dim@desktop:~/Desktop$ /usr/local/bin/slowmoFlowBuilder -v
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!

**Comment by valgit** [comment]
Well, I think you are on the bug "library inconsistencies" (here : https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-319/+bug/1248642 and here : http://ubuntuforums.org/showthread.php?t=2247911). But I can't help you more, as I have no NVIDIA card on my ubuntu server.

**Comment by dim162** [comment]
Thank you
