### ISSUE TITLE
Mac build errors

### ISSUE THREAD

**Issue by fulldecent** [slowmoVideo/slowmoVideo#27]
I am building with Mac using:

    brew install cmake glew ffmpeg zlib yasm qt4 x264
    cmake ../slowmoVideo/src -DCMAKE_INSTALL_PREFIX=/Users/val/Applications/slowmoVideo -DQTDIR=/Users/val/Documents/Sources/qt4 -DQT_MAKE_EXECUTABLE=/Users/val/Documents/Sources/qt4/bin/qmake -DOpenCV_DIR=/Users/val/Documents/Sources/opencv/share/OpenCV -DGLEW_INCLUDE_DIR=/Users/val/Documents/Sources/slowlib/include -DGLEW_LIBRAIRIES=/Users/val/Documents/Sources/slowlib/lib/libGLEW.a -DJPEG_INCLUDE_DIR=/Users/val/Documents/Sources/slowlib/include -DJPEG_LIBRARY=/Users/val/Documents/Sources/slowlib/lib/libjpeg.a -DFFMPEG_LIBRARY_DIR=/Users/val/Documents/Sources/ffmpeg/lib -DFFMPEG_INCLUDE_PATHS="/Users/val/Documents/Sources/ffmpeg/include"
    make -k

Here are the errors:

 > › make -k
 > [  3%] Built target V3D
 > [  6%] Built target sV
 > [  9%] Built target sVencode
 > [ 11%] Built target sVflow
 > [ 12%] Built target sVinfo
 > [ 12%] Built target sVvis
 > [ 15%] Built target sVgui
 > [ 15%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o
 > In file included from /Users/williamentriken/Developer/slowmoVideo/src/slowmoVideo/project/project_sV.cpp:16:
 > /Users/williamentriken/Developer/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.h:19:10: fatal error: 'opencv2/video/tracking.hpp' file not found
 > #include "opencv2/video/tracking.hpp"
 >          ^
 > 1 error generated.
 > make[2]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o] Error 1
 > [ 16%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/flowSourceOpenCV_sV.cpp.o
 > In file included from /Users/williamentriken/Developer/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.cpp:12:
 > /Users/williamentriken/Developer/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.h:19:10: fatal error: 'opencv2/video/tracking.hpp' file not found
 > #include "opencv2/video/tracking.hpp"
 >          ^
 > 1 error generated.
 > make[2]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/flowSourceOpenCV_sV.cpp.o] Error 1
 > [ 16%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/work_flow.cpp.o
 > In file included from /Users/williamentriken/Developer/slowmoVideo/src/slowmoVideo/project/work_flow.cpp:6:
 > /Users/williamentriken/Developer/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.h:19:10: fatal error: 'opencv2/video/tracking.hpp' file not found
 > #include "opencv2/video/tracking.hpp"
 >          ^
 > 1 error generated.
 > make[2]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/work_flow.cpp.o] Error 1
 > make[2]: Target '
 > slowmoVideo/project/CMakeFiles/sVproj.dir/build' not remade because of errors.
 > make[1]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/all] Error 2
 > [ 16%] Built target slowmoInterpolate
 > [ 17%] Built target slowmoVideoInfo
 > [ 23%] Built target slowmoFlowEdit
 > [ 24%] Built target slowmoInfo
 > [ 25%] Built target slowmoVisualizeFlow
 > [ 25%] Built target AvconvInfo
 > Linking CXX executable encodeFramesTest
 > Undefined symbols for architecture x86_64:
 >   "_eatARGB", referenced from:
 >       _main in ffmpegTestEncodeFrames.cpp.o
 >   "_eatSample", referenced from:
 >       _main in ffmpegTestEncodeFrames.cpp.o
 >   "_finish", referenced from:
 >       _main in ffmpegTestEncodeFrames.cpp.o
 >   "_prepare", referenced from:
 >       _main in ffmpegTestEncodeFrames.cpp.o
 > ld: symbol(s) not found for architecture x86_64
 > clang: error: linker command failed with exit code 1 (use -v to see invocation)
 > make[2]: *** [slowmoVideo/test/encodeFramesTest] Error 1
 > make[2]: Target '
 > slowmoVideo/test/CMakeFiles/encodeFramesTest.dir/build' not remade because of errors.
 > make[1]: *** [slowmoVideo/test/CMakeFiles/encodeFramesTest.dir/all] Error 2
 > Linking CXX executable encodeTest
 > Undefined symbols for architecture x86_64:
 >   "_eatSample", referenced from:
 >       _main in encodeTest.c.o
 >   "_finish", referenced from:
 >       _main in encodeTest.c.o
 >   "_prepareDefault", referenced from:
 >       _main in encodeTest.c.o
 > ld: symbol(s) not found for architecture x86_64
 > clang: error: linker command failed with exit code 1 (use -v to see invocation)
 > make[2]: *** [slowmoVideo/test/encodeTest] Error 1
 > make[2]: Target '
 > slowmoVideo/test/CMakeFiles/encodeTest.dir/build' not remade because of errors.
 > make[1]: *** [slowmoVideo/test/CMakeFiles/encodeTest.dir/all] Error 2
 > make[2]: *** No rule to make target '
 > /Users/val/Documents/Sources/slowlib/lib/libjpeg.a', needed by '
 > V3D/Apps/GL/slowmoFlowBuilder'.
 > make[2]: Target '
 > V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/build' not remade because of errors.
 > make[1]: *** [V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/all] Error 2
 > make[1]: Target '
 > all' not remade because of errors.
 > make: *** [all] Error 2
 > make: Target '
 > default_target' not remade because of errors.

**Comment by valgit** [comment]
Well, it seems you have not install OpenCV or you give the wrong path to env/cmake for it ! In your cake command you should change my own path by yours ;-)

**Comment by fulldecent** [comment]
Ah, sorry I was expecting `#include <...>` for library paths... I'm looking into it now

**Comment by fulldecent** [comment]
Attempt 2. Here is the install process I am using:

''''
brew install cmake glew ffmpeg zlib yasm qt4 x264 homebrew/science/opencv

cmake ../slowmoVideo/src -DCMAKE_INSTALL_PREFIX=/Users/val/Applications/slowmoVideo -DQTDIR=/Users/val/Documents/Sources/qt4 -DQT_MAKE_EXECUTABLE=/Users/val/Documents/Sources/qt4/bin/qmake -DOpenCV_DIR=/Users/val/Documents/Sources/opencv/share/OpenCV -DGLEW_INCLUDE_DIR=/Users/val/Documents/Sources/slowlib/include -DGLEW_LIBRAIRIES=/Users/val/Documents/Sources/slowlib/lib/libGLEW.a -DJPEG_INCLUDE_DIR=/Users/val/Documents/Sources/slowlib/include -DJPEG_LIBRARY=/Users/val/Documents/Sources/slowlib/lib/libjpeg.a -DFFMPEG_LIBRARY_DIR=/Users/val/Documents/Sources/ffmpeg/lib -DFFMPEG_INCLUDE_PATHS="/Users/val/Documents/Sources/ffmpeg/include"

make -k
''''

And result:

 > › make -k 
 > [  3%] Built target V3D
 > [  6%] Built target sV
 > [  9%] Built target sVencode
 > [ 11%] Built target sVflow
 > [ 12%] Built target sVinfo
 > [ 12%] Built target sVvis
 > [ 15%] Built target sVgui
 > [ 36%] Built target sVproj
 > [ 36%] Built target slowmoInterpolate
 > [ 37%] Built target slowmoVideoInfo
 > Linking CXX executable slowmoUI.app/Contents/MacOS/slowmoUI
 > Undefined symbols for architecture x86_64:
 >   "_NSClassFromString", referenced from:
 >       MacNotificationHandler::showNotification(QString const&, QString const&) in macnotificationhandler.mm.o
 >       MacNotificationHandler::hasUserNotificationCenterSupport() in macnotificationhandler.mm.o
 >   "_NSLog", referenced from:
 >       VideoQT::exportFrames(QString, int, RenderTask_sV*) in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSAppleScript", referenced from:
 >       objc-class-ref in macnotificationhandler.mm.o
 >   "_OBJC_CLASS_$_NSAutoreleasePool", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSBitmapImageRep", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSFileManager", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSImage", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSNumber", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSString", referenced from:
 >       objc-class-ref in macnotificationhandler.mm.o
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_QTMovie", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_QTAddImageCodecQuality", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 >   "_QTAddImageCodecType", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 >   "_QTMakeTime", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 >   "_QTMovieEditableAttribute", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 >   "_QTTrackTimeScaleAttribute", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 > ld: symbol(s) not found for architecture x86_64
 > clang: error: linker command failed with exit code 1 (use -v to see invocation)
 > make[2]: ~~~ [slowmoVideo/slowmoUI/slowmoUI.app/Contents/MacOS/slowmoUI] Error 1
 > make[2]: Target 'slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/build' not remade because of errors.
 > make[1]: ~~~ [slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/all] Error 2
 > [ 43%] Built target slowmoFlowEdit
 > [ 44%] Built target slowmoInfo
 > Linking CXX executable slowmoRenderer
 > Undefined symbols for architecture x86_64:
 >   "_NSLog", referenced from:
 >       VideoQT::exportFrames(QString, int, RenderTask_sV*) in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSAutoreleasePool", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSBitmapImageRep", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSFileManager", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSImage", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSNumber", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_NSString", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_OBJC_CLASS_$_QTMovie", referenced from:
 >       objc-class-ref in libsVencode.a(qtkit.mm.o)
 >   "_QTAddImageCodecQuality", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 >   "_QTAddImageCodecType", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 >   "_QTMakeTime", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 >   "_QTMovieEditableAttribute", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 >   "_QTTrackTimeScaleAttribute", referenced from:
 >       VideoQT::VideoQT(int, int, double, char const*, char const*, char const*) in libsVencode.a(qtkit.mm.o)
 > ld: symbol(s) not found for architecture x86_64
 > clang: error: linker command failed with exit code 1 (use -v to see invocation)
 > make[2]: ~~~ [slowmoVideo/slowmoRenderer/slowmoRenderer] Error 1
 > make[2]: Target 'slowmoVideo/slowmoRenderer/CMakeFiles/slowmoRenderer.dir/build' not remade because of errors.
 > make[1]: ~~~ [slowmoVideo/slowmoRenderer/CMakeFiles/slowmoRenderer.dir/all] Error 2
 > [ 45%] Built target slowmoVisualizeFlow
 > [ 45%] Built target AvconvInfo
 > [ 46%] Built target Test
 > Linking CXX executable encodeFramesTest
 > Undefined symbols for architecture x86_64:
 >   "_eatARGB", referenced from:
 >       _main in ffmpegTestEncodeFrames.cpp.o
 >   "_eatSample", referenced from:
 >       _main in ffmpegTestEncodeFrames.cpp.o
 >   "_finish", referenced from:
 >       _main in ffmpegTestEncodeFrames.cpp.o
 >   "_prepare", referenced from:
 >       _main in ffmpegTestEncodeFrames.cpp.o
 > ld: symbol(s) not found for architecture x86_64
 > clang: error: linker command failed with exit code 1 (use -v to see invocation)
 > make[2]: ~~~ [slowmoVideo/test/encodeFramesTest] Error 1
 > make[2]: Target 'slowmoVideo/test/CMakeFiles/encodeFramesTest.dir/build' not remade because of errors.
 > make[1]: ~~~ [slowmoVideo/test/CMakeFiles/encodeFramesTest.dir/all] Error 2
 > Linking CXX executable encodeTest
 > Undefined symbols for architecture x86_64:
 >   "_eatSample", referenced from:
 >       _main in encodeTest.c.o
 >   "_finish", referenced from:
 >       _main in encodeTest.c.o
 >   "_prepareDefault", referenced from:
 >       _main in encodeTest.c.o
 > ld: symbol(s) not found for architecture x86_64
 > clang: error: linker command failed with exit code 1 (use -v to see invocation)
 > make[2]: ~~~ [slowmoVideo/test/encodeTest] Error 1
 > make[2]: Target 'slowmoVideo/test/CMakeFiles/encodeTest.dir/build' not remade because of errors.
 > make[1]: ~~~ [slowmoVideo/test/CMakeFiles/encodeTest.dir/all] Error 2
 > Linking CXX executable UnitTests
 > Undefined symbols for architecture x86_64:
 >   "QTest::qExec(QObject*, int, char STAR STAR )", referenced from:
 >       _main in testAll.cpp.o
 >   "QTest::qVerify(bool, char const*, char const*, char const*, int)", referenced from:
 >       TestFlowRW_sV::testWriteAndRead() in testFlowRW_sV.cpp.o
 >       TestFlowRW_sV::testWriteAndReadFail() in testFlowRW_sV.cpp.o
 >       TestFlowField_sV::slotTestConstructorOpenGL() in testFlowField_sV.cpp.o
 >       TestFlowField_sV::slotTestGaussKernel() in testFlowField_sV.cpp.o
 >       TestFlowField_sV::slotTestMedian() in testFlowField_sV.cpp.o
 >       TestVector_sV::testLength() in testVector_sV.cpp.o
 >       TestVector_sV::testAdd() in testVector_sV.cpp.o
 >       ...
 > ld: symbol(s) not found for architecture x86_64
 > clang: error: linker command failed with exit code 1 (use -v to see invocation)
 > make[2]: ~~~ [slowmoVideo/unittests/UnitTests] Error 1
 > make[2]: Target 'slowmoVideo/unittests/CMakeFiles/UnitTests.dir/build' not remade because of errors.
 > make[1]: ~~~ [slowmoVideo/unittests/CMakeFiles/UnitTests.dir/all] Error 2
 > make[2]: ~~~ No rule to make target '/Users/val/Documents/Sources/slowlib/lib/libjpeg.a', needed by 'V3D/Apps/GL/slowmoFlowBuilder'.
 > make[2]: Target 'V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/build' not remade because of errors.
 > make[1]: ~~~ [V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/all] Error 2
 > make[1]: Target 'all' not remade because of errors.
 > make: ~~~ [all] Error 2
 > make: Target 'default_target' not remade because of errors.

**Comment by fulldecent** [comment]
And here are some patching that are helping compile: 

````
--- a/src/cmake/FindFFMPEG.cmake
+++ b/src/cmake/FindFFMPEG.cmake
@@ -142,7 +142,7 @@ endif()
 
 # On OS X we ffmpeg libraries depend on VideoDecodeAcceleration and CoreVideo frameworks
 IF (APPLE)
-    SET(FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} "-framework CoreFoundation -framework QuartzCore -framework VideoDecodeAccel
+    SET(FFMPEG_LIBRARIES ${FFMPEG_LIBRARIES} "-framework CoreFoundation -framework ApplicationServices -framework QuartzC ENDIF()
 
 
diff --git a/src/slowmoVideo/lib/qtkit.mm b/src/slowmoVideo/lib/qtkit.mm
index bd5d671..124f32c 100644
--- a/src/slowmoVideo/lib/qtkit.mm
+++ b/src/slowmoVideo/lib/qtkit.mm
@@ -5,6 +5,7 @@
 #include <QDebug>
 #include <QtCore/QSettings>
 #include <QImage>
+#import <QTKit/QTKit.h>
 
 #include "qtkit.h"
 #include "video_enc.h"
````

**Comment by valgit** [comment]
you should add a ‘-DENABLE_TESTS=OFF‘ to your cake command and also a ‘-D USE_QTKIT=ON‘ to have quicktime included on OSX.
normally the ‘#import <QTKit/QTKit.h>‘ is in qtkit.h so I didn't understand your patch !
hope this help.
