### ISSUE TITLE
"fixup_bundle: not a valid bundle" on Debian Jessie

### ISSUE THREAD

**Issue by Findus23** [slowmoVideo/slowmoVideo#28]
I tried to compile slowmoVideo on Debian Jessie. At first make complained about something, but after changing the line to 
`cmake ../src -DUSE_QTKIT=FALSE -DENABLE_TESTS=FALSE`
(as suggested in #18 ) it worked.
But my problem is that `sudo make install` aborts with the following error:
```
-- executable file 1: /usr/local/bin/slowmoFlowEdit
-- executable file 2: /usr/local/bin/slowmoVideoInfo
-- executable file 3: /usr/local/bin/slowmoInterpolate
-- executable file 4: /usr/local/slowmoUI
-- verified='1'
-- info='Verified 4 executable files in '/usr/local''
-- 
-- verified='1'
-- info=''
-- 
-- fixup_bundle: done
-- Up-to-date: /usr/local/bin/slowmoFlowEdit
-- fixup_qt4_executable
--   executable='/usr/local/slowmoFlowEdit'
--   qtplugins=''
--   libs=''
--   dirs='/usr/lib/x86_64-linux-gnu;/usr/lib/x86_64-linux-gnu/qt4/bin'
--   plugins_dir=''
--   request_qt_conf=''
-- fixup_bundle
--   app='/usr/local/slowmoFlowEdit'
--   libs=''
--   dirs='/usr/lib/x86_64-linux-gnu;/usr/lib/x86_64-linux-gnu/qt4/bin'
-- warning: *NOT* handled - directory/file does not exist...
CMake Error at /usr/share/cmake-3.0/Modules/BundleUtilities.cmake:730 (message):
  error: fixup_bundle: not a valid bundle
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/DeployQt4.cmake:199 (fixup_bundle)
  slowmoVideo/slowmoFlowEdit/cmake_install.cmake:54 (FIXUP_QT4_EXECUTABLE)
  cmake_install.cmake:42 (include)


Makefile:66: recipe for target 'install' failed
make: *** [install] Error 1
```

The whole log can be found here: https://gist.github.com/Findus23/07749ceb30041733dbc9

What am I missing? Alternatively: How else can I install slowmoVideo on Debian Jessie?

**Comment by valgit** [comment]
I will look at how you can install it ! for now as far as I know the problem is that there is no working equivalent for DeployQT4 in QT5 !!!

**Comment by valgit** [comment]
Hi,

I have commit an update for the installed part. can you check if it work for you ?

thanks

**Comment by Findus23** [comment]
Thanks for the help.
It seems to install

But there is still a problem. There is no `slowmoUI` in `/usr/local/bin/`
```
lukas@kinderzimmer:~/slowmoVideo/build$ /usr/local/bin/slowmo
slowmoFlowBuilder    slowmoFlowEdit       slowmoInterpolate    slowmoRenderer       slowmoVideoInfo      slowmoVisualizeFlow  
```
Maybe there is something useful in the log: https://gist.github.com/Findus23/07749ceb30041733dbc9

**Comment by valgit** [comment]
from your log, it seems to be installed in 
-- executable file 4: /usr/local/slowmoUI
-- executable file 5: /usr/local/slowmoFlowEdit 
!!!
well, maybe I missed another parameter in install part !
can you check that ?

**Comment by Findus23** [comment]
Okay, that was my mistake, it's there and working.

One final question: Is it normal that only the cpu Flow Method is working. (I have a Nvidia graphic card; There is nothing to select in both dropdown menus)

![bildschirmfoto vom 2015-03-11 16 37 07](https://cloud.githubusercontent.com/assets/6266037/6599964/e8ccb124-c80c-11e4-80fe-bf36b1514092.png)

**Comment by valgit** [comment]
from your log, I see that flowBuilder as been built (in /usr/local/bin/slowmoFlowBuilder), you should try to set the path in the "binary locations"

**Comment by Findus23** [comment]
Unfortunately it stays red (no matter if I type the path or browse it)
and when I press Ok and reopen the settings everything is like before. 
![bildschirmfoto vom 2015-03-11 16 57 49](https://cloud.githubusercontent.com/assets/6266037/6601644/1cbc71e0-c817-11e4-96f0-981a5b80fcb3.png)

**Comment by valgit** [comment]
Can you give the output of "/usr/local/bin/slowmoFlowBuilder -v" ?

**Comment by Findus23** [comment]
That explains why it's not working:
It's the same as `slowmoFlowBuilder`: "Speicherzugriffsfehler" (segmentation fault)
I'm running 64 bit.
```
lukas@kinderzimmer:~$ uname -a
Linux kinderzimmer 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt4-3 (2015-02-03) x86_64 GNU/Linux
```

**Comment by valgit** [comment]
well, not sure about the 64 bit  reason, more probably as in my config a conflict between old GLSL code (openGL 2.0 with propriatary extensions)  and new openGL 3.x.  But I am not sufficiently fluent with OpenGL/GLSL to find what need to be update, as the flow builder code is "way too old" ;-)
maybe you could try to install OpenCL driver and compile OpenCV with it, and see if the OpenCV-OpenCL irk for you ?

**Comment by Findus23** [comment]
>maybe you could try to install OpenCL driver and compile OpenCV with it, and see if the OpenCV-OpenCL irk for you ?

I think I am not able to do so. I am just a normal Linux-User and I have no Idea about OpenCV.
But as long as slowmoVideo is working my problem is solved.
Thanks for helping.
