### ISSUE TITLE
Download link for slowmoVideo missing!

### ISSUE THREAD

**Issue by GoGoGoPro** [slowmoVideo/slowmoVideo#30]
Hello,

where is the download link of this software?
I can't find it anywhere!

Thanks.

**Comment by lyra833** [comment]
What OS are you using?

**Comment by GoGoGoPro** [comment]
Windows 7

**Comment by GoGoGoPro** [comment]
There is no exe file in there: https://github.com/slowmoVideo/slowmoVideo/releases

(see version 0.4)

**Comment by lyra833** [comment]
Someone please correct me if I'm wrong, but I think the most recent Windows binary we have is [Version 3.1](http://slowmovideo.granjow.net/builds/slowmoVideo_0.3.1+d356d79_win32.zip). I'll see if I can compile and add some binaries to the repo this week.

**Comment by GoGoGoPro** [comment]
Do you mean that you can compile version 0.4?

This would be great! THANK YOU IN ADVANCE!

**Comment by lyra833** [comment]
I'm off from school this week, so I should have some time to give it a shot.

**Comment by GoGoGoPro** [comment]
This would be great! Thank you so much! Please just comment again here that I know if you have updated the version! Thanks ;-)

**Comment by valgit** [comment]
for those who are looking for binaries you can find them here : 
for windows 64 bits : http://www.mediafire.com/download/23tbebr8aqy1bxc/slomovideo.7z
for osx : http://www.mediafire.com/download/cbwf4y8q7fm33j0/slowmoVideo_osx.zip
they are tag "0.3" but are really "0.4" as the tag as been set just after the compilation !

**Comment by GoGoGoPro** [comment]
Sorry, but I can't open this link.
Can you please send me the file (Windows 64 bits) directly to this address: gogogopro@outlook.com
Thank you very much in advance!

**Comment by valgit** [comment]
can you try with this other link : http://dl.free.fr/mWRDz2jZ8

**Comment by GoGoGoPro** [comment]
Thank you! Fantastic! It works!

**Comment by GoGoGoPro** [comment]
Sorry, but there is no EXE file in the download folder. How do I start the app?

**Comment by valgit** [comment]
there should be an exe ! what file did you download ?

**Comment by GoGoGoPro** [comment]
This link from you which is no longer valid: http://dl.free.fr/mWRDz2jZ8

After downloading there were a couple of files, but no exe file.

**Comment by valgit** [comment]
have you try this one : http://www.mediafire.com/download/23tbebr8aqy1bxc/slomovideo_win64.7z
