### ISSUE TITLE
Change path of gpumat.hpp

### ISSUE THREAD

**Issue by kuboosoft** [slowmoVideo/slowmoVideo#32]
Now Fedora Linux, Opencv (opencv-devel) isn't include /usr/include/opencv2/gpu/gpumat.hpp , the correct path is /usr/include/opencv2/core/gpumat.hpp"
I made a symlink and compiled fine, but isn't correct.

**Comment by Granjow** [comment]
Is maybe the CMake cache outdated? Does it work with a fresh build directory?

**Comment by kuboosoft** [comment]
Yes is a fresh build; I made a rpm of slowmoVideo the last year, I will update to version 0.4, I use mock. With mock I can find all lost dependencies and work a virgen chroot.

About mock: http://fedoraproject.org/wiki/Projects/Mock

**Comment by valgit** [comment]
what is your version of opencv ?

**Comment by kuboosoft** [comment]
@valgit opencv-2.4.9-3

**Comment by valgit** [comment]
I've check my ubuntu the /usr/include/opencv2/gpu/gpumat.hpp only include /usr/include/opencv2/core/gpumat.hpp !!

**Comment by hahn** [comment]
got error like this. 
in project/flowSourceOpenCV_sV.cpp still use path gpu
