### ISSUE TITLE
Missing opencv2/ocl/ocl.hpp

### ISSUE THREAD

**Issue by Keeo** [slowmoVideo/slowmoVideo#36]
During *make* I got stuck at opencv dependency. I looked into opencv folder and found *ocl.hpp* file in core folder. But changing path yield in wrong namespace.
```make
[ 19%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o
In file included from /home/keo/slowmo/slowmoVideo/src/slowmoVideo/project/project_sV.cpp:16:0:
/home/keo/slowmo/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.h:25:31: fatal error: opencv2/ocl/ocl.hpp: Adresář nebo soubor neexistuje
 #include "opencv2/ocl/ocl.hpp"
```

*Mint with opencv2 installed firstly from apt-get and later build from source.*

**Comment by valgit** [comment]
I think those headers have moved to "core", I will check.

**Comment by valgit** [comment]
After check, it seems that : you didn't install the opencv-ocl package or you did not compile your opencv with OCL activated.

**Comment by valgit** [comment]
@Keeo , @vylaern could you recheck with latest patch ?

**Comment by Keeo** [comment]
Sorry, It was year ago and I don't have environment anymore to test that

**Comment by Vylaern** [comment]
I recompiled nvidia-cuda-toolkit yesterday and opencv with cuda and opencl flag, did not help.
Now I compile also nvidia-cuda-sdk, maybe this was missing, will rebot system and check again. Then I will try your source again as well and let you know. I also have gdb installed in the case.

**Comment by Vylaern** [comment]
I could confirm, I have no errors during compilations (source from git) and slowmoUI starts.
I am going with my other problems back to: https://github.com/slowmoVideo/slowmoVideo/issues/98#issuecomment-249626918

**Comment by valgit** [comment]
@Vylaern thanks for your check.
