### ISSUE TITLE
Qt-related compile error on OS X

### ISSUE THREAD

**Issue by forthrin** [slowmoVideo/slowmoVideo#39]
When I run "make" on OS X, I get compile errors which seems related to Qt.

Linking CXX executable slowmoUI.app/Contents/MacOS/slowmoUI
Undefined symbols for architecture x86_64:
  "_CGColorSpaceCreateWithName", referenced from:
      qt_mac_image_to_cgimage(QImage const&) in libsVencode.a(qtkit.mm.o)

There were a dozen similar other ones too. Please help.

**Comment by valgit** [comment]
what was your cmake command ? you seems to be missing some OSX parts...

**Comment by forthrin** [comment]
I installed all the dependencies using Homebrew. Running `cmake ../slowmoVideo/src` finds all the required libraries and say's it ready to build, even without adding the `-D` flags (which seem to point to the author's personal home directory anyway). Both Qt4 and Qt5 give the same compile error. If you want the full output from the make process, please send me your email address.

**Comment by valgit** [comment]
seems you are missing some OSX framework. can you rerun with : cmake ../slowmoVideo/src -DUSE-QTKIT=true to be sure that all Quicktime & co are added ?

**Comment by forthrin** [comment]
Oh... I assumed Qt was related to Trolltech, but evidently it's
QuickTime. Honest mistake!

cmake ../slowmoVideo/src -DUSE-QTKIT=true
CMake Warning:
  Manually-specified variables were not used by the project:
    USE-QTKIT

make
[ 37%] Built target slowmoVideoInfo
Linking CXX executable slowmoUI.app/Contents/MacOS/slowmoUI
Undefined symbols for architecture x86_64:
  "_CGColorSpaceCreateWithName", referenced from:
      qt_mac_image_to_cgimage(QImage const&) in libsVencode.a(qtkit.mm.o)

Don't know if the following page is relevant, but it hints at
including AppKit, however how would I do that if that is the solution?

http://code.opencv.org/issues/2038

**Comment by valgit** [comment]
well, I made myself a mistake it's USE_QTKIT with an underscore !! Normally including Quicktime should suffice to have AppKit included by dependancies, let see.

**Comment by forthrin** [comment]
Yes, cmake now seems to accept the QTKIT option. It still gives some
warnings, but don't know if they're relevant:

CMake Warning (dev) at V3D/Config/v3d_macros.cmake:36 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "V3d2" of target "slowmoFlowBuilder" does not exist.
Call Stack (most recent call first):
  V3D/Apps/GL/CMakeLists.txt:6 (add_v3d_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

Anyway, the problem persists in the make process:

[ 72%] Building CXX object
slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/qrc_resources.cpp.o
Linking CXX executable slowmoUI.app/Contents/MacOS/slowmoUI
Undefined symbols for architecture x86_64:
  "_CGColorSpaceCreateWithName", referenced from:
      qt_mac_image_to_cgimage(QImage const&) in libsVencode.a(qtkit.mm.o)

**Comment by valgit** [comment]
well, I've check my build dir, I've got -framework Cocoa -framework QTKit -framework QuartzCore -framework AppKit -framework OpenCL set but I can't find where sit comes from ! I was thinking they where set by Quicktime rules in FindQTKit.cmake.
* maybe you can run your cmake in verbose mode just to see ?
*  in cmakelist.txt there are lines (around line 198)  with EXTERNAL_LIBS...., can you add the missing framework there just to test ?

thanks

**Comment by forthrin** [comment]
github does not support uploading of text files. Do you have an email address I can send the compile log to?

**Comment by valgit** [comment]
maybe you can paste the last lines ? or paste bin ?

**Comment by forthrin** [comment]
http://pastebin.com/StPcbQdW (valid for 24 hours)

**Comment by valgit** [comment]
Hi,
I look at your log, how did you compile OpenCv, it seems that you did not include Cocoa and quicktime ?
in the mean time for testing, can you add : `set(ADDITIONAL_LIBS "-framework AppKit")` around line 170 of `src/CMakeLists.txt` ?
like :
    ```
if (APPLE AND USE_QTKIT)
                find_package(QTKIT)
                message(STATUS "QTKIT find at ${QTKIT_LIBRARY} ")
           set(ADDITIONAL_LIBS "-framework AppKit")
        endif()
```

**Comment by forthrin** [comment]
Followed your suggestion and this is what happened:

[ 55%] Building CXX object
slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/moc_macnotificationhandler.cpp.o
Linking CXX executable slowmoUI.app/Contents/MacOS/slowmoUI
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_QTMovie", referenced from:
      objc-class-ref in libsVencode.a(qtkit.mm.o)
  "_QTAddImageCodecQuality", referenced from:
      VideoQT::VideoQT(int, int, double, char const*, char const*,
char const*) in libsVencode.a(qtkit.mm.o)
  "_QTAddImageCodecType", referenced from:
      VideoQT::VideoQT(int, int, double, char const*, char const*,
char const*) in libsVencode.a(qtkit.mm.o)
  "_QTMakeTime", referenced from:
      VideoQT::VideoQT(int, int, double, char const*, char const*,
char const*) in libsVencode.a(qtkit.mm.o)
  "_QTMovieEditableAttribute", referenced from:
      VideoQT::VideoQT(int, int, double, char const*, char const*,
char const*) in libsVencode.a(qtkit.mm.o)
  "_QTTrackTimeScaleAttribute", referenced from:
      VideoQT::VideoQT(int, int, double, char const*, char const*,
char const*) in libsVencode.a(qtkit.mm.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [slowmoVideo/slowmoUI/slowmoUI.app/Contents/MacOS/slowmoUI] Error 1
make[1]: *** [slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/all] Error 2
make: *** [all] Error 2

**Comment by valgit** [comment]
well, very strange ! what's your OSX and xcode version ?
you now seems to be missing Quicktime !
maybe use framework Cocoa -framework QTKit -framework QuartzCore -framework AppKit -framework OpenCL instead of only -framework AppKit ?

**Comment by forthrin** [comment]
I got further, but another error occurs:

[ 83%] Building CXX object
slowmoVideo/test/CMakeFiles/encodeFramesTest.dir/ffmpegTestEncodeFrames.cpp.o
Linking CXX executable encodeFramesTest
Undefined symbols for architecture x86_64:
  "_eatARGB", referenced from:
      _main in ffmpegTestEncodeFrames.cpp.o
  "_eatSample", referenced from:
      _main in ffmpegTestEncodeFrames.cpp.o
  "_finish", referenced from:
      _main in ffmpegTestEncodeFrames.cpp.o
  "_prepare", referenced from:
      _main in ffmpegTestEncodeFrames.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [slowmoVideo/test/encodeFramesTest] Error 1
make[1]: *** [slowmoVideo/test/CMakeFiles/encodeFramesTest.dir/all] Error 2
make: *** [all] Error 2

**Comment by valgit** [comment]
Hi, I'am glad to see that this "patch" is working ! I will try to validate it. 
for the other part, as said in some previous issues, you should add `-DENABLE_TESTS=FALSE` to the cmake command, as all the "testing" code as not been update for now.

**Comment by forthrin** [comment]
I'm happy to inform you that the compilation process is now complete!
You should update your project accordingly. I look forward to trying
the tool and hope it will work out of the box :)

Added to src/CMakeLists.txt:
set(ADDITIONAL_LIBS "-framework Cocoa -framework QTKit -framework
QuartzCore -framework AppKit -framework OpenCL")

Compile command:
cmake ../slowmoVideo/src -DUSE_QTKIT=true -DENABLE_TESTS=FALSE
