### ISSUE TITLE
Core Dumped on Bad Frame Rate

### ISSUE THREAD

**Issue by sobotka** [slowmoVideo/slowmoVideo#40]
When changing the display frame rate via Preferences, if a small fraction is entered the app will Abort. Example such as 24/1001.

    ASSERT: "false" in file /Develop/Sources/slowmoVideo/src/slowmoVideo/project/nodeList_sV.cpp,
    line 100
    Aborted (core dumped)

**Comment by valgit** [comment]
are you sure about the message ?
because around line 100 I'v got : 
  qDebug() << "No node before " << targetTime;
        Q_ASSERT(false);
        if (m_list.size() > 0) {
            srcTime = m_list[0].y();
        }

so you should have some previous messages which would be useful !

**Comment by valgit** [comment]
this should be ok by 14ceb08 commit
