### ISSUE TITLE
Segfault when rendering

### ISSUE THREAD

**Issue by ss32** [slowmoVideo/slowmoVideo#43]
I successfully rendered a series of small images, but ran into a segfault when trying to render a larger image.  This happens when trying to render either the full resolution or a preview.  

threading info :  4 
("slowmoUI") 
Adding  "Input monitor"  to the menu's widget list 
Adding  "Curve monitor"  to the menu's widget list 
Adding  "Render preview"  to the menu's widget list 
Adding unique key  "h" 
Adding unique key  "q" 
Adding unique key  "n" 
Adding unique key  "o" 
Adding unique key  "s" 
Adding unique key  "a" 
Adding unique key  "d" 
Adding unique key  "t" 
Adding unique key  "m" 
"/home/scott/slowmoVideo/build/beach3.sVproj" 
Reading project file: version 2.7
Project directory:  "/home/scott/slowmoVideo/build" 
App name:  "slowmoVideo" 
Script engine initialized for function  0x7fff51796f70 
Canvas: Project loaded from  Project_sV(0x2265e40) 
Frame source:  ImagesFrameSource_sV(0x2233c00) 
tMaxY set to  4.16667 
cache flow source disable 
Segment  0 :  "Left node: 0; selected: 0" 
rendering worker start in Thread  0x7f7636790a40 
Starting rendering process in Thread  0x7f758ffff700 
Frame snapping in from  0  to  0 
Rendering frame number  0  @ 0  from source time  0.04 
Building flow for left frame  0  to right frame  1 ; Size:  Original frame size 
Arguments:  ("/home/scott/deepdream/beach/00000.jpg", "/home/scott/deepdream/beach/0000001.jpg", "/home/scott/slowmoVideo/build/cache/oFlowOrig/forward-lambda20.00_0-1.sVflow", "20", "100") 
Optical flow built for  "/home/scott/slowmoVideo/build/cache/oFlowOrig/forward-lambda20.00_0-1.sVflow"  in  20  ms 
"" "" 
"Failed to read width/height from file /home/scott/slowmoVideo/build/cache/oFlowOrig/forward-lambda20.00_0-1.sVflow" 
Flow building error:  "Failed to read width/height from file /home/scott/slowmoVideo/build/cache/oFlowOrig/forward-lambda20.00_0-1.sVflow" 
Failed creating optical flow, falling back to OpenCV ... 
Failed attempts so far:  1 
check GPU 
CUDA support :  0 found 
OpenCL support 
modprobe: ERROR: could not insert 'fglrx': No such device
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: ERROR: could not insert 'fglrx': No such device
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
modprobe: ERROR: could not insert 'fglrx': No such device
Error! Fail to load fglrx kernel module! Maybe you can switch to root user to load kernel module directly
plateform : AMD Accelerated Parallel Processing vendor: Advanced Micro Devices, Inc.
plateform : NVIDIA CUDA vendor: NVIDIA Corporation
Device : 0 GeForce GTX 480 is present
end OpenCL support 
Re-using existing flow image for left frame 0 to right frame 1: "/home/scott/slowmoVideo/build/cache/oFlowOrig/ocv-forward-0-1.sVflow"
Read flow file of size 400×171. Magic number: flow_sV, version: 1
Re-using existing flow image for left frame 1 to right frame 0: "/home/scott/slowmoVideo/build/cache/oFlowOrig/ocv-backward-1-0.sVflow"
Read flow file of size 400×171. Magic number: flow_sV, version: 1
Segmentation Fault

**Comment by ss32** [comment]
I also get an error when trying to manually interpolate the images

slowmoInterpolate forward 00000.jpg 0000001.jpg 
Arg: forward
Running forward flow.
Arg: 00000.jpg
Arg: 0000001.jpg
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted

**Comment by valgit** [comment]
Hi,
can you "force" the use of software optical flow instead of OpenCL driver ?

**Comment by ss32** [comment]
How do I go about doing that?

**Comment by valgit** [comment]
You can check your slowmovideo preferences !

**Comment by ss32** [comment]
easy enough, I will check and let you know

**Comment by ss32** [comment]
I tried changing to CPU opencv and openCL on my GPU but both resulted in the same error.

**Comment by valgit** [comment]
could you run it under gdb, and post the back trace result when set fault occur ?

**Comment by valgit** [comment]
I think that i find what's goes wrong. it seems that in some cases, extracting frame take too long. This should be corrected in last commit  ffa46c3.
