### ISSUE TITLE
What open source licence is this under?

### ISSUE THREAD

**Issue by enetheru** [slowmoVideo/slowmoVideo#45]

**Comment by enetheru** [comment]
I'm concerned because there is at least 9 committers already for this project, but since there is no licence agreement listed anywhere, not on the website, not in the repository that i can find. i fear that this project will eventually run into a wall.

I guess implicitly if you haven't purchased a licence for QT then  GPL/LGPL 3 or 2.1
but that's a guess, i'm no expert.

seems a major oversight IMHO.

**Comment by Granjow** [comment]
GPL. For me, LGPL is fine too. I will let @valgit decide.

**Comment by valgit** [comment]
Hi,

I am ok with GPL too. maybe we should set it explicitly everywhere ?

**Comment by Granjow** [comment]
Ok! Added LICENSE.md in 3ff98c9f913479377a7542630907eaf8c5739406
