### ISSUE TITLE
Debian Jessie cannot open video source

### ISSUE THREAD

**Issue by funkydiscoman** [slowmoVideo/slowmoVideo#50]
Running Debian Jessie.
Compiled after:   cmake ../src -DUSE_QTKIT=FALSE -DENABLE_TESTS=FALSE

I have avconv and no ffmpeg on the system which I'm guessing may be the issue. Any suggestions are very welcome.

Video Source information shows--------------------------
Number of video streams: -1
Frames: 0
Size: 1x0
Frame rate: 0/0

--------------------------------------------------------------------

Terminal output------------------------------------------------
threading info :  4 
("slowmoUI") 
Adding  "Input monitor"  to the menu's widget list 
Adding  "Curve monitor"  to the menu's widget list 
Adding  "Render preview"  to the menu's widget list 
Adding unique key  "h" 
Adding unique key  "q" 
Adding unique key  "n" 
Adding unique key  "o" 
Adding unique key  "s" 
Adding unique key  "a" 
Adding unique key  "d" 
Adding unique key  "t" 
Adding unique key  "m" 
Reading info for file /home/xxx/Desktop/trim.MP4.
output :  "" 
Could not find size.

------------------------------------------------------------------------

**Comment by valgit** [comment]
avconv should work, can you check it's correctly find under preferences ? and that it work on your file : avconv -i /home/xxx/Desktop/trim.MP4 ?

**Comment by funkydiscoman** [comment]
The preferences by default has "ffmpeg", setting it to "/usr/bin/avconv" fixes it. Thanks.
