### ISSUE TITLE
Error compiling: 

### ISSUE THREAD

**Issue by politvs** [slowmoVideo/slowmoVideo#51]
Hi everybody!

I would really like to try this interesting piece of software, but I'm experimenting some problems compiling it under Linux Mint 17.1 (Ubuntu 14.04 based)

I'm following these instructions:

https://github.com/slowmoVideo/slowmoVideo/wiki/Download#compiling

But a while after typing make I get the next error:

<pre>Linking CXX executable slowmoUI
../lib/libsVencode.a(video_enc.cpp.o): In function `CreateVideoWriter(char const*, int, int, double, int, char const*)':
/home/politvs/slowmoVideo/src/slowmoVideo/lib/video_enc.cpp:11: undefined reference to `CreateVideoWriter_QT(char const*, int, int, double, char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [slowmoVideo/slowmoUI/slowmoUI] Error 1
make[1]: *** [slowmoVideo/slowmoUI/CMakeFiles/slowmoUI.dir/all] Error 2
make: *** [all] Error 2
</pre>

Any hints?

TIA

**Comment by valgit** [comment]
in w way, yes ... instructions on the wiki are a bit old...
under linux you need to use : `cmake ../src -DUSE_QTKIT=FALSE -DENABLE_TESTS=FALSE`
as QT_KIT is only usefull under OSX.
(take a look at issues #34 or #18 and #28 for more information)

**Comment by politvs** [comment]
Now it compile. Thanks for your quick help!
