### ISSUE TITLE
slowmoUI menus

### ISSUE THREAD

**Issue by pgillet** [slowmoVideo/slowmoVideo#54]
Hi,

When I run slowmoUI on Ubuntu 14.04, I don't have the top menus slowmoVideo UI, View and Help (I saw them in a tutorial video on YouTube).

Note: I use the Cinnamon desktop environment that is based on the GTK+ 3 toolkit, but I get the same result with Gnome or Unity anyway.

I successfully created a test project, but I can't actually render it. So I tried slowmoRenderer in command line as follows:

slowmoRenderer test.sVproj -size small -fps 24 -interpolation twoway -target video ./result.mpg auto -v3dLambda 8.0

I got an "empty" video that lasts around 10 seconds, which is the duration that I have "edited".

Can you help?

Thank you very much,

Pascal

**Comment by valgit** [comment]
sure ! can you post your console logs from the application ? so we can see if there is a problem ! as in my ubuntun 14 all is going well !

**Comment by pgillet** [comment]
Hi,

This is all I got:

threading info :  8 
("slowmoUI") 
Adding  "Input monitor"  to the menu's widget list 
Adding  "Curve monitor"  to the menu's widget list 
Adding  "Render preview"  to the menu's widget list 
Adding unique key  "h" 
Adding unique key  "q" 
Adding unique key  "n" 
Adding unique key  "o" 
Adding unique key  "s" 
Adding unique key  "a" 
Adding unique key  "d" 
Adding unique key  "t" 
Adding unique key  "m" 

Is there a log file somewhere that can help you?

**Comment by valgit** [comment]
helas, no, it's the normal startup ! which QT version did you use ?

**Comment by pgillet** [comment]
This is libqt4-dev and this is the most recent version.
I followed the install instructions for Ubuntu.

**Comment by pgillet** [comment]
OK, I found a solution by means of this post: [Using KDE - Application Menus Missing in Qt Apps] (http://askubuntu.com/questions/452079/using-kde-application-menus-missing-in-qt-apps)
I ended up unsetting the QT_QPA_PLATFORMTHEME environment variable, and the application menus are there, and the rendering is much better!

Thank you, great app!

Maybe this is something you could add to your troubleshooting section...

**Comment by valgit** [comment]
I think you should update to QT5 !

**Comment by pgillet** [comment]
OK, I'll give it a try!

But I still end up with blank videos, with the good duration though.
Do you think it is related to these old instructions?

**Comment by valgit** [comment]
not sure ;-) can you post the logs ?

**Comment by pgillet** [comment]
AT least the end of them:

...
Re-using existing flow image for left frame 52675 to right frame 52676: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-forward-52675-52676.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
Re-using existing flow image for left frame 52676 to right frame 52675: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-backward-52676-52675.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
  Saved frame number  547  to  "/tmp/slowmoUI-h7p5B7/rendered-00548.png" 
Rendering frame number  548  @ 22.8333  from source time  878.803 
Re-using existing flow image for left frame 52675 to right frame 52676: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-forward-52675-52676.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
Re-using existing flow image for left frame 52676 to right frame 52675: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-backward-52676-52675.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
  Saved frame number  548  to  "/tmp/slowmoUI-h7p5B7/rendered-00549.png" 
Rendering frame number  549  @ 22.875  from source time  878.803 
Re-using existing flow image for left frame 52675 to right frame 52676: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-forward-52675-52676.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
Re-using existing flow image for left frame 52676 to right frame 52675: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-backward-52676-52675.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
  Saved frame number  549  to  "/tmp/slowmoUI-h7p5B7/rendered-00550.png" 
Rendering frame number  550  @ 22.9167  from source time  878.804 
Re-using existing flow image for left frame 52675 to right frame 52676: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-forward-52675-52676.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
Re-using existing flow image for left frame 52676 to right frame 52675: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-backward-52676-52675.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
  Saved frame number  550  to  "/tmp/slowmoUI-h7p5B7/rendered-00551.png" 
Rendering frame number  551  @ 22.9583  from source time  878.804 
Re-using existing flow image for left frame 52675 to right frame 52676: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-forward-52675-52676.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
Re-using existing flow image for left frame 52676 to right frame 52675: "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/cache/oFlowSmall/ocv-backward-52676-52675.sVflow"
Read flow file of size 320×180. Magic number: flow_sV, version: 1
  Saved frame number  551  to  "/tmp/slowmoUI-h7p5B7/rendered-00552.png" 
Rendering : exporting 
exporting temporary frame to Video "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/test.mpg"  using codec  "" starting at  1 
exporting frame from :  "/tmp/slowmoUI-h7p5B7/rendered-%05d.png"  to  /media/ubuntu/data/Downloads/Mont Blanc/slowmo/test.mpg 
Arguments:  ("-f", "image2", "-start_number", "1", "-i", "/tmp/slowmoUI-h7p5B7/rendered-%05d.png", "-r", "24", "-vcodec", "libx264", "-s", "320x180", "/media/ubuntu/data/Downloads/Mont Blanc/slowmo/test.mpg") 
"" 
"" 
0 
Rendering stopped after  "" 
Rendering process finished in Thread  0x7f68a64be700

**Comment by valgit** [comment]
I didn't see any errors appart the file name which end in mpg not in mp4 ! can you check that ? (use a filename in mp4  like test.mp4 ?)  how/why did you render in small size ?

**Comment by pgillet** [comment]
Ok, it works well and the result is beyond my expectations! Sorry for the loss of time on this second part!

Thank you.
