### ISSUE TITLE
Command Line Usage?

### ISSUE THREAD

**Issue by Miserlou** [slowmoVideo/slowmoVideo#62]
Would be love to use this as a command-line tool, I just want to slow down videos, I don't need a whole GUI.

ex
    $ slowmo input.mp4 --time 2x--output output.mp4

**Comment by gwegner** [comment]
I second this. There is the "slomoRenderer" - a commandline tool already available.
Unfortunately, it needs a full XMP project file. I'd appreciate an option to just add a multiplicator (could be a float from 0..1) to set the level of slow motion. So 0.5 would be half the speed.
I'm considering to promote the tool for the time lapse community (I'm the developer of LRTimelapse, see http://lrtimelapse.com) - but I'd need an easier solution to trigger it. Thanks for considering this!

**Comment by valgit** [comment]
@gwegner, I like this idea two ! your proposal is interesting, I was aware of **slowmoRenderer**, what you said make me think of using the factor (0..1) to update a template project file or something like that to be able to run it ?!

**Comment by Miserlou** [comment]
I like the float idea as well.

**Comment by Miserlou** [comment]
I also imagine that having a CLI version would reduce dependencies, so it would be easier to make OSX/W32 builds as you wouldn't have to worry about QT anymore.

**Comment by gwegner** [comment]
That's what I think, just a lean command line utility, that can be launched in background to do the job. Would be great to have it for mac too.

**Comment by valgit** [comment]
@Miserlou : it would not reduce dependencies, as lot's of slowmo code use QT object and hierarchy, it's not only the GUI parts ! as for the build, OSX is easy once you have statisfied all dependencies (cake, ffmpeg, opencv ...), as for W32, the big problem is that VisualStudio break on lot's of syntax ! so you need to fallback to gcc in cross compilation with for e.g. cygwin.
@gwegner mac would of course work !

**Comment by Granjow** [comment]
@valgit Oh, Please don't. Trying to compile it on Visual Studio is probably the worst thing you can do to yourself, there is hardly anything more terrible.

I have generated the Windows executables with [MXE](http://mxe.cc/). This should still work, and used to run without problems (unless there were internal dependency problems that ffmpeg could not be compiled because libx264 could not be compiled because something else could not be … you get the point). Not sure if the CMake file still runs after all the adjustments, but in the git history you should still find adjustments I had to do back then.

**Comment by valgit** [comment]
@Granjow  I've try VisualStudioas I was wanting a real native win64, and QT,cake should be portable ! but well as i said i fall back to compile with cygwin, which was already complicated.I've try MXE but was not satisfied. In another ways, my main station is a mac, so I prefer OSX ;-)
I'm in the process to **convert** slowmoRenderer to full CLI, but I'm block with the fact that ** slowmoRenderer** expect an already frame-split video.

**Comment by Granjow** [comment]
@valgit Okay, what did not work with MXE? But if cygwin works, that's fine :)

Maybe it is a good idea to combine all in one executable and just add a parameter to slowmoVideo so the UI would be started with `slowmoVideo` and the renderer with `slowmoVideo infile.sVproj` or `slowmoVideo infile.avi --export-avi=out.avi --speed=0.1` …

**Comment by Miserlou** [comment]
Strongly advice against having it launch the GUI, the whole reason for a
CLI interface is to avoid that. Windows builds are less important since
Windows is an inherently GUI environment. OSX and Linux builds would be far
more useful for automation purposes.

From my phone..

**Comment by gwegner** [comment]
Windows is, what most users use. There is no reason for not having a windows CLI application. Windows users are mostly more tech savy then Mac os users... :-)

**Comment by Granjow** [comment]
@Miserlou Sorry if I have not been clear enough. It is just about combining it in one executable. Inkscape, for example, does this as well: You can run 

    inkscape --export-png=test.png test.svg

and it will convert the SVG to PNG, without any UI. Works perfectly also on web servers.

**Comment by valgit** [comment]
I've made a PR for a new command line version, can you review and check.
@gwegner can you tell me if it works for you in LRTimelapse ? moreover can you tell me what is needed to include it directly (lib ?)

**Comment by valgit** [comment]
partially done in commit  ffa46c3

**Comment by Miserlou** [comment]
Sweet! Any documentation on how to use this?

**Comment by valgit** [comment]
@Miserlou, @gwegner  here an usage  exemple : 
`./slowmoRenderer -input video ~/Videos/MVI_0233.AVI -target video cli_test.mp4 auto -slowfactor 0.5`
where `-input` is your source, `-target`is your output file and `slowfactor`is the factor you want to apply, other old `slowmoRenderer `are usable.

**Comment by Miserlou** [comment]
Excellent!
