### ISSUE TITLE
Curve monitor eating all ram

### ISSUE THREAD

**Issue by petrica-celrau** [slowmoVideo/slowmoVideo#69]
System: Intel i5, GPU integrated - driver=i915 , 8GB ram, Arch Linux
As mentioned on G+ slowmovideo was using up all my 8GB of ram as I was moving the mouse around in the grid area. I was wrong in believing it was a Qt5 vs. Qt4 issue, turns out if I uncheck the curve monitor in the view menu slomowvideo behaves normally.

**Comment by valgit** [comment]
@petrica-celrau can you give more hint on how to reproduce/look at the problem ?
for now, the only thing I see is a change in all "monitor", not just "curve", where there is now a cache of image instead of loading them each time (less IO workload but more memory ...).
so maybe, there is a bug in the cache part (which is using qt qcache) ?

**Comment by petrica-celrau** [comment]
Open slowmoVideo, load a project so that you have images in both monitors
and move the cursor in the grid area, in my case as I move the cursor I can
see in conky the amount of ram used increasing... and it stops only when I
stop the mouse or run out of ram in which case the display is blocked.
Anyway, thanks for looking into it.

**Comment by petrica-celrau** [comment]
Honestly, I never understood the purpose of Curve monitor and Render preview, AFAIC you can just get rid of them.

**Comment by valgit** [comment]
hi @petrica-celrau , the PR #73 should correct your memory problems and also your window setting.
can you test it ?

**Comment by petrica-celrau** [comment]
Looks good thanks. One small detail, un-checking Curve/Render monitor in
View menu is now saved for the next session but the menu still shows all
checked. Not a big deal really.

**Comment by valgit** [comment]
yes, I've seen this effect, but don't find from where it come !

**Comment by petrica-celrau** [comment]
must be hard-coded somewhere..

**Comment by valgit** [comment]
@petrica-celrau the latest commits should now correct this last bug !

**Comment by petrica-celrau** [comment]
Thanks, will check it out tomorrow.

**Comment by petrica-celrau** [comment]
all is good!
