### ISSUE TITLE
extracted frames in new project are not saved in project's folder

### ISSUE THREAD

**Issue by petrica-celrau** [slowmoVideo/slowmoVideo#72]
Forgot about this bug but every time I create a new project all frames are saved in ~/ instead of the project folder. Even if I create a new project in an existing folder. If I move the frames folder in the project folder and restart the app it reads them from there.
Arch linux.

**Comment by valgit** [comment]
this should be corrected in latest commit @petrica-celrau, can you check ?

**Comment by petrica-celrau** [comment]
Oh yes, maybe I wasn't clear in my previous post, everything is saved where it should be now, thanks.
