### ISSUE TITLE
About window displays wrong version number

### ISSUE THREAD

**Issue by PandaJim** [slowmoVideo/slowmoVideo#75]
Just built the 0.5 release for ubuntu, but the about window does not display correct version.

I'm not a programmer,  it displays version 0.3.1 in about dialog even after made below change to  src/CMakeList.txt:

set(PROJECT_VERSION_MAJOR "0")
set(PROJECT_VERSION_MINOR "5")
set(PROJECT_VERSION_PATCH "0")

here are deb packages:
https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/slowmovideo/+packages

**Comment by Granjow** [comment]
The version number is defined here:
https://github.com/slowmoVideo/slowmoVideo/blob/master/src/slowmoVideo/lib/defs_sV.hpp

**Comment by PandaJim** [comment]
fixed, thanks!

**Comment by valgit** [comment]
@PandaJim I would only said that it's "up to date". I think there is a need for better version handling.

**Comment by valgit** [comment]
close by PR #79
