### ISSUE TITLE
No top menu on Lubuntu 14.04

### ISSUE THREAD

**Issue by itf** [slowmoVideo/slowmoVideo#80]
On Lubuntu 14.04 there is no top menu when using the UI, which makes it impossible to render the video. Ubuntu 14.04 doesn't have this prolem.

**Comment by valgit** [comment]
Hi @itf , I wasn't know what was _Lubuntu _! nwo after some google search I now know it's for LXDE !.
After some more researching, it's seem it's a more general problem with Lubuntu  (see: https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619  ). Can you test/check what they say ? like removing** appmenu-qt5** (I don't kown what it's use for ;-)

**Comment by itf** [comment]
removing appmenu-qt5  solved the problem!  Thanks!
