### ISSUE TITLE
Current source is uanble to build V3D in any Linux distribution

### ISSUE THREAD

**Issue by pmo-19** [slowmoVideo/slowmoVideo#84]
The current source I did checkout today is unable to build V3D in any Linux distribution.

**Comment by pmo-19** [comment]
OpenGL, GLUT and GLEW are installed properly however the following message pops up:
`* OpenGL could not be found.`
`* GLUT could not be found.`
`* GLEW could not be found.`
`* V3D will be built:                        ---NO---`

**Comment by pmo-19** [comment]
The disturbance is the side effect of one of my patches. You can close as invalid.

**Comment by valgit** [comment]
close by PR #86
