### ISSUE TITLE
Current Git source is unable to build V3D in any Linux distribution [Confirmed]

### ISSUE THREAD

**Issue by pmo-19** [slowmoVideo/slowmoVideo#87]
I am very sorry but after further investigation this evening, I confirm I stand by my initial report.
Your current `Git master source checked out yesterday` and available in my [own PPA](https://launchpad.net/~anton+/+archive/ubuntu/photo-video-apps) with packages `slowmovideo-qt4` and `slowmovideo` (qt5) couldn't build `V3D`:
`* OpenGL could not be found.`
`* GLUT could not be found.`
`* GLEW could not be found.`
`* (ok) JPEG libraries found at /usr/include: /usr/lib/x86_64-linux-gnu/libjpeg.so`
`* (ok) PNG libraries found at /usr/include;/usr/include`
`* V3D will be built:                        ---NO---`
As I had not enough time this morning to confirm it I thought it has to deal with my many patches, but it's not. To further confirm the failure from your Git source I did try to build this evening with the `debian folder` from `Mr. Hermann Voßeler` your official supplier and it fails in the same way as with my folder.
However the previously released version `0.5` is working fine. When I have time I will publish packages for this release.
May be `Mr. Hermann Voßeler` @Ichthyostega can help you out ? as he is fluent in many capabilities, according to his own statements.
I will not. So long. Enjoy the ride :-)

**Comment by valgit** [comment]
you have not pull the latest commit from pr #86 I think, please check with that, don't be so proud.
