### ISSUE TITLE
Unable to build current (2016-05-22) on Arch Linux

### ISSUE THREAD

**Issue by evertvorster** [slowmoVideo/slowmoVideo#89]
I am the maintainer for the slowmovideo package in Arch Linux. 
I need a bit of help with the compilation of this software. It used to compile fine not too long ago. 

Currently, the source from git does not build. Here is an error log:

==> Building and installing package
==> Making package: slowmovideo-git 20160408-1 (Sun May 22 11:52:31 CEST 2016)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating slowmoVideo git repo...
Fetching origin
==> Validating source files with md5sums...
    slowmoVideo ... Skipped
==> Extracting sources...
  -> Creating working copy of slowmoVideo git repo...
Cloning into 'slowmoVideo'...
done.
==> Starting pkgver()...
==> Starting build()...
-- The C compiler identification is GNU 6.1.1
-- The CXX compiler identification is GNU 6.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using qt5
Qt libraries found at : Qt5::Gui /  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libavformat'
--   Found libavformat, version 57.25.100
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.24.102
-- Checking for module 'libavutil'
--   Found libavutil, version 55.17.103
-- Checking for module 'libswscale'
--   Found libswscale, version 4.0.100
-- checking: avformat.h
--           /usr/include/libavformat
-- checking: avcodec.h
--           /usr/include/libavcodec
-- checking: avutil.h
--           /usr/include/libavutil
-- checking: swscale.h
--           /usr/include/libswscale
-- FFMPEG libraries are at /usr/lib64/libavformat.so;/usr/lib64/libavcodec.so;/usr/lib64/libavutil.so;/usr/lib64/libswscale.so
-- slowmoInfo Bundle will be :  =>  slowmoVideo 
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found GLUT: /usr/lib64/libglut.so  
-- Found JPEG: /usr/lib64/libjpeg.so  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib64/libpng.so (found version "1.6.21") 

======================V3D============================
* (info) Installation prefix: /usr.
         (Can be adjusted with -DCMAKE_INSTALL_PREFIX=your_path.  Default: .)
* (info) Shaders will be included in the binary: YES
         (Can be disabled with the cmake flag -DDISABLE_INCLUDE_SOURCE)
* (ok) OpenGL found in /usr/include: /usr/lib64/libGLU.so;/usr/lib64/libGL.so
* (ok) GLUT found in /usr/include: /usr/lib64/libglut.so;/usr/lib64/libXmu.so;/usr/lib64/libXi.so
* (ok) GLEW found at /usr/include/GL
* (ok) JPEG libraries found at /usr/include: /usr/lib64/libjpeg.so
* (ok) PNG libraries found at /usr/include;/usr/include
* V3D will be built:                        ---YES---
==================slowmoVideo========================
* (info) slowmoVideo installation goes to /usr.
         (Can be adjusted with -DCMAKE_INSTALL_PREFIX=your_path. Default is .)
* (ok) ffmpeg found at 
* (ok) OpenCV 3.1.0 found at .
* slowmoVideo will be built:                ---YES---
=======================END===========================

-- Configuring done
CMake Warning (dev) at V3D/Config/v3d_macros.cmake:36 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "V3d2" of target "slowmoFlowBuilder" does not exist.
Call Stack (most recent call first):
  V3D/Apps/GL/CMakeLists.txt:6 (add_v3d_executable)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/build
Scanning dependencies of target V3D
[  0%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/glsl_shaders.cpp.o
[  1%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/v3d_gpubase.cpp.o
[  1%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/v3d_gpuflow.cpp.o
/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/V3D/GL/v3d_gpuflow.cpp:103:4: warning: ‘void {anonymous}::upsampleBuffers(unsigned int, unsigned int, float, float, V3D_GPU::FrameBufferObject&)’ defined but not used [-Wunused-function]
    upsampleBuffers(unsigned src1Tex, unsigned src2Tex, float scale1, float scale2,
    ^~~~~~~~~~~~~~~
/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/V3D/GL/v3d_gpuflow.cpp:67:4: warning: ‘void {anonymous}::upsampleBuffer(unsigned int, float, V3D_GPU::FrameBufferObject&)’ defined but not used [-Wunused-function]
    upsampleBuffer(unsigned srcTex, float scale, FrameBufferObject& dstFbo)
    ^~~~~~~~~~~~~~
/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/V3D/GL/v3d_gpuflow.cpp:17:4: warning: ‘void {anonymous}::upsampleDisparities(unsigned int, unsigned int, float, V3D_GPU::RTT_Buffer&, V3D_GPU::RTT_Buffer&)’ defined but not used [-Wunused-function]
    upsampleDisparities(unsigned uvSrcTex, unsigned pSrcTex, float pScale,
    ^~~~~~~~~~~~~~~~~~~
[  2%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/v3d_gpucolorflow.cpp.o
/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/V3D/GL/v3d_gpucolorflow.cpp:74:4: warning: ‘void {anonymous}::upsampleDisparities(unsigned int, unsigned int, unsigned int, float, V3D_GPU::RTT_Buffer&, V3D_GPU::RTT_Buffer&, V3D_GPU::RTT_Buffer&)’ defined but not used [-Wunused-function]
    upsampleDisparities(unsigned uvSrcTex, unsigned pSrcTex, unsigned qSrcTex, float pScale,
    ^~~~~~~~~~~~~~~~~~~
[  2%] Building CXX object CMakeFiles/V3D.dir/V3D/GL/v3d_gpupyramid.cpp.o
[  3%] Building CXX object CMakeFiles/V3D.dir/V3D/Base/v3d_image.cpp.o
[  3%] Linking CXX static library libV3D.a
[  3%] Built target V3D
Scanning dependencies of target sVflow
[  3%] Building CXX object slowmoVideo/lib/CMakeFiles/sVflow.dir/flowRW_sV.cpp.o
[  4%] Building CXX object slowmoVideo/lib/CMakeFiles/sVflow.dir/flowField_sV.cpp.o
[  4%] Building CXX object slowmoVideo/lib/CMakeFiles/sVflow.dir/flowTools_sV.cpp.o
[  5%] Building CXX object slowmoVideo/lib/CMakeFiles/sVflow.dir/kernel_sV.cpp.o
[  6%] Linking CXX static library libsVflow.a
[  6%] Built target sVflow
[  7%] Generating moc_ffmpeg_writer.cpp
Scanning dependencies of target sVencode
[  7%] Building CXX object slowmoVideo/lib/CMakeFiles/sVencode.dir/ffmpeg_writer.cpp.o
/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/lib/ffmpeg_writer.cpp:70:0: warning: ignoring #pragma mark  [-Wunknown-pragmas]
 #pragma mark -
 
/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/lib/ffmpeg_writer.cpp:133:0: warning: ignoring #pragma mark  [-Wunknown-pragmas]
 #pragma mark -
 
/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/lib/ffmpeg_writer.cpp:134:0: warning: ignoring #pragma mark C [-Wunknown-pragmas]
 #pragma mark C bridge
 
[  8%] Building CXX object slowmoVideo/lib/CMakeFiles/sVencode.dir/video_enc.cpp.o
[  8%] Building CXX object slowmoVideo/lib/CMakeFiles/sVencode.dir/moc_ffmpeg_writer.cpp.o
[  9%] Linking CXX static library libsVencode.a
[  9%] Built target sVencode
Scanning dependencies of target sVinfo
[  9%] Building CXX object slowmoVideo/lib/CMakeFiles/sVinfo.dir/videoInfo_sV.cpp.o
[ 10%] Building CXX object slowmoVideo/lib/CMakeFiles/sVinfo.dir/avconvInfo_sV.cpp.o
[ 10%] Linking CXX static library libsVinfo.a
[ 10%] Built target sVinfo
Scanning dependencies of target sV
[ 11%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/defs_sV.cpp.o
[ 12%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/vector_sV.cpp.o
[ 12%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/shutter_sV.cpp.o
[ 13%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/intMatrix_sV.cpp.o
[ 13%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/interpolate_sV.cpp.o
[ 14%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/bezierTools_sV.cpp.o
[ 14%] Building CXX object slowmoVideo/lib/CMakeFiles/sV.dir/sourceField_sV.cpp.o
[ 15%] Linking CXX static library libsV.a
[ 15%] Built target sV
Scanning dependencies of target sVvis
[ 16%] Building CXX object slowmoVideo/lib/CMakeFiles/sVvis.dir/flowVisualization_sV.cpp.o
[ 16%] Linking CXX static library libsVvis.a
[ 16%] Built target sVvis
[ 17%] Generating moc_combinedShortcuts.cpp
[ 17%] Generating moc_imageDisplay.cpp
Scanning dependencies of target sVgui
[ 17%] Building CXX object slowmoVideo/libgui/CMakeFiles/sVgui.dir/imageDisplay.cpp.o
[ 18%] Building CXX object slowmoVideo/libgui/CMakeFiles/sVgui.dir/combinedShortcuts.cpp.o
[ 18%] Building CXX object slowmoVideo/libgui/CMakeFiles/sVgui.dir/moc_imageDisplay.cpp.o
[ 19%] Building CXX object slowmoVideo/libgui/CMakeFiles/sVgui.dir/moc_combinedShortcuts.cpp.o
[ 20%] Linking CXX static library libsVgui.a
[ 20%] Built target sVgui
[ 20%] Generating moc_work_flow.cpp
[ 21%] Generating moc_project_sV.cpp
[ 21%] Generating moc_renderTask_sV.cpp
[ 22%] Generating moc_abstractFrameSource_sV.cpp
[ 23%] Generating moc_imagesFrameSource_sV.cpp
[ 23%] Generating moc_videoFrameSource_sV.cpp
[ 24%] Generating moc_emptyFrameSource_sV.cpp
Scanning dependencies of target sVproj
[ 25%] Building CXX object slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o
In file included from /tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/project_sV.cpp:16:0:
/tmp/yaourt-tmp-evert/aur-slowmovideo-git/src/slowmoVideo/src/slowmoVideo/project/flowSourceOpenCV_sV.h:23:35: fatal error: opencv2/core/gpumat.hpp: No such file or directory
 #include "opencv2/core/gpumat.hpp"
                                   ^
compilation terminated.
slowmoVideo/project/CMakeFiles/sVproj.dir/build.make:90: recipe for target 'slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o' failed
make[2]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/project_sV.cpp.o] Error 1
CMakeFiles/Makefile2:391: recipe for target 'slowmoVideo/project/CMakeFiles/sVproj.dir/all' failed
make[1]: *** [slowmoVideo/project/CMakeFiles/sVproj.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build slowmovideo-git.
==> Restart building slowmovideo-git ? [y/N]

**Comment by valgit** [comment]
at first I would say that there is a problem with OpenCV version/installation. What version of OpenCV is it ? where is it installed ?

**Comment by evertvorster** [comment]
Hi there...

At the head of the compile log, it says it finds opencv 3.1

Arch also has an older version of opencv, but the two versions can not be
concurrently installed, and the other version is a required dependency of
software that I want installed....

It may be that OpenCV has changed quite a bit between major versions.
-Evert-

On 22 May 2016 at 15:46, valgit <notifications@github.com> wrote:

> at first I would say that there is a problem with OpenCV
> version/installation. What version of OpenCV is it ? where is it installed ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/slowmoVideo/slowmoVideo/issues/89#issuecomment-220833355>
>



-- 
Evert Vorster
Isometrix Acquistion Superchief
(Streamer Handling)

**Comment by valgit** [comment]
I haven't look in depth in OpenCV 3.x but I've already seen that significant change have been done which require a porting/updating of the slowmovideo code for work with it.

**Comment by valgit** [comment]
FWIW: OpenCV 3.x versus OpenCV 2.X, and how to port :
http://docs.opencv.org/3.1.0/db/dfa/tutorial_transition_guide.html#gsc.tab=0
http://stackoverflow.com/questions/29750616/maintaining-code-compatibility-between-opencv-2-and-opencv-3

**Comment by poupouneroot** [comment]
oh no.
i'm not a dev but this software it's so great and i'm on a archlinux too.
thank you for your work but i'm reading your link for the transiton but it's much hard for me to apply.

**Comment by valgit** [comment]
I'm working on it ! in the mean time, i think using _OpenCV_ 2.x is the best alternative in your case

**Comment by poupouneroot** [comment]
thank for you reply but this solution is not conseivable because on archlinux opencv3 is the default with his dependency for other software already installed. archlinux is a rolling distribution with his advantages and his disadvantages

**Comment by valgit** [comment]
close by PR #91

**Comment by evertvorster** [comment]
It compiles against OpenCV3 now. 
Thank you for the hard work!

**Comment by poupouneroot** [comment]
merci beaucoup.
