### ISSUE TITLE
flowBuilder on Windows?

### ISSUE THREAD

**Issue by if13b023** [slowmoVideo/slowmoVideo#90]
Hi,
I am using Windows10, the Windows binaries from the website and the correct ffmpeg version. The programs works in CPU mode but GPU would be even better ;)
I've searched on different websites, comment sections and one (not so nice) issue on this github page for information about a windows-flowBuilder binary.
The most recent answer to this question is from 2014, which says "no, there is no flowBuilder for windows".
Is this still correct? Am I missing something?

**Comment by valgit** [comment]
Yes, nobody have been able to port this old "flowBuilder" to new OSes and/or other OSes

**Comment by if13b023** [comment]
So there is currently no way to use the GPU on Windows?
(maybe seems like a stupid question but I couldn't find anything about this in the documentation)

**Comment by valgit** [comment]
as of today there is no way to use a GPU for slowmovideo under Windows nor OSX, even under Linux there is some limitations
