### ISSUE TITLE
X11

### ISSUE THREAD

**Issue by asymystry** [slowmoVideo/slowmoVideo#92]
hi all,

total software neophyte here encountering this on 'make':

[ 99%] Linking CXX executable slowmoFlowBuilder
cd /Users/resno6/dev/slowmoVideo/V3D/Apps/GL && /usr/local/Cellar/cmake/3.5.2/bin/cmake -E cmake_link_script CMakeFiles/slowmoFlowBuilder.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -Wall  -g -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/slowmoFlowBuilder.dir/flowBuilder.cpp.o CMakeFiles/slowmoFlowBuilder.dir/__/__/__/slowmoVideo/lib/flowField_sV.cpp.o CMakeFiles/slowmoFlowBuilder.dir/__/__/__/slowmoVideo/lib/flowRW_sV.cpp.o  -o slowmoFlowBuilder  -L/Users/resno6/dev/slowmoVideo/src/V3D  ../../../libV3D.a /usr/local/lib/libjpeg.dylib /usr/local/lib/libpng.dylib /usr/lib/libz.dylib -framework OpenGL /usr/local/lib/libGLEW.dylib -framework GLUT -lX11 -Wl,-rpath,/Users/resno6/dev/slowmoVideo/src/V3D 
ld: library not found for -lX11
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [V3D/Apps/GL/slowmoFlowBuilder] Error 1
make[1]: *** [V3D/Apps/GL/CMakeFiles/slowmoFlowBuilder.dir/all] Error 2
make: *** [all] Error 2

i think i have x11 installed in /opt/X11/, is this just a matter of changing a path somewhere? (where?/how?) can i provide other useful information? any thoughts are much appreciated

**Comment by valgit** [comment]
from what I see, you are trying compiling under OSX. If, so, then don't bother trying to compile V3D, it doesn't work on OSX even in X11 mode.

**Comment by asymystry** [comment]
thanks for the response valgit, and one more question: are there any known ways around this to run slowmoVideo on osx or am i better off trying something else for optical flow?

**Comment by valgit** [comment]
@asymystry slowmovideo can run natively under OS X, no need for X11 ! you juste need QT5, and openCV. (not the latest version but you can check this : http://www.mediafire.com/download/weg32e02q75bbyy/slowmoVideo_10.7.zip for eg).
There is only the V3D part which doesn't work.
