### ISSUE TITLE
Lossless output

### ISSUE THREAD

**Issue by Spekular** [slowmoVideo/slowmoVideo#93]
As far as I can tell, there's no way to output lossless frames from slowmoVideo. It would be nice to have .png output or something similar for this purpose. Otherwise you end up losing quite a bit of data going from source footage->slow footage->edited footage->online compression on youtube etc.

Maybe there's a good reason this doesn't exist or I'm just not understanding how to do it, in which case I'm sorry :octocat:

**Comment by valgit** [comment]
@Spekular if you want png output, you should select "images" as your ouput format in the render dialog.

**Comment by Spekular** [comment]
@valgit I was confused because the default filenam ends with .jpg. I didn't realize renamongnit would change the actual output. Thanks, and sorry for the bad issue!

**Comment by valgit** [comment]
@Spekular no problem ! In another way, I wonder if png should not be the default instead of jpeg ?

**Comment by Spekular** [comment]
@valgit that would make sense.
