### ISSUE TITLE
"ERROR: could not open display" after building on centOS

### ISSUE THREAD

**Issue by quindo** [slowmoVideo/slowmoVideo#94]
I believe I have built all of the dependencies for slowmoVideo, but I receive the following error.  After it displays the following it just hangs and a reboot is needed to get back to the command line.  Does anyone have any ideas on what my problem might be?

> [root@localhost ~]# pkg-config --modversion opencv
2.4.5

>[root@localhost ~]# slowmoRenderer
slowmoRenderer for slowmoVideo v0.5-37-g5512607

>[root@localhost TestDirForVideos]#  slowmoRenderer -target video EasyModeslow.mp                                                                                                                                                             4 auto -input video EasyMode.mp4 -slowfactor .9 -start :start -end :end -interpo                                                                                                                                                             lation twoway2 -size orig
Standalone Rendering.
  target dir   QDir( "/tmp/rendered" , nameFilters = { * },  QDir::SortFlags( Na                                                                                                                                                             me | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Reading info for file EasyMode.mp4.
output :  "ffmpeg version 2.6.8 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-4)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --i                                                                                                                                                             ncdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86                                                                                                                                                             _64 --optflags='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-                                                                                                                                                             protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=gen                                                                                                                                                             eric' --enable-bzlib --disable-crystalhd --enable-gnutls --enable-ladspa --enabl                                                                                                                                                             e-libass --enable-libcdio --enable-libdc1394 --enable-libfaac --enable-nonfree -                                                                                                                                                             -enable-libfdk-aac --enable-nonfree --disable-indev=jack --enable-libfreetype --                                                                                                                                                             enable-libgsm --enable-libmp3lame --enable-openal --enable-libopenjpeg --enable-                                                                                                                                                             libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-lib                                                                                                                                                             speex --enable-libtheora --enable-libvorbis --enable-libv4l2 --enable-libx264 --                                                                                                                                                             enable-libx265 --enable-libxvid --enable-x11grab --enable-avfilter --enable-avre                                                                                                                                                             sample --enable-postproc --enable-pthreads --disable-static --enable-shared --en                                                                                                                                                             able-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-runt                                                                                                                                                             ime-cpudetect
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'EasyMode.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.46.100
  Duration: 00:00:11.04, start: 0.000000, bitrate: 3826 kb/s
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yu                                                                                                                                                             v420p, 1920x1080 [SAR 1:1 DAR 16:9], 3824 kb/s, 25 fps, 25 tbr, 12800 tbn, 50 tb                                                                                                                                                             c (default)
    Metadata:
      handler_name    : VideoHandler
      timecode        : 00:00:00:00
    Stream #0:1(eng): Data: none (tmcd / 0x64636D74), 0 kb/s
    Metadata:
      handler_name    : TimeCodeHandler
      timecode        : 00:00:00:00
At least one output file must be specified
"
Found avconv/ffmpeg executable at  "/TestDirForVideos/ffmpeg"
        Distribution:  ffmpeg
Extracting frames with  "ffmpeg" ("-i", "EasyMode.mp4", "-f", "image2", "/tmp/fr                                                                                                                                                             ames/orig/frame%05d.png")
""
""
ffmpeg in   16054 ms
will slow down to : 0.9
Segment  0 :  "Left node: 0; selected: 0"
Starting rendering process in Thread  139979539516096
Rendering Slow-Mo ?
Frame snapping in from  0  to  0
Rendering frame number  0  @ 0  from source time  0
No interpolation necessary.
  Saved frame number  0  to  "/tmp/rendered/rendered-00001.png"
Rendering frame number  1  @ 0.0416667  from source time  0.0375
Building flow for left frame  0  to right frame  1 ; Size:  Original frame size
Arguments:  ("/tmp/frames/orig/frame00001.png", "/tmp/frames/orig/frame00002.png", "/tmp/cache/oFlowOrig/forward-lambda20.00_0-1.sVflow", "20", "100")
Failed:  "ERROR: could not open display
" "TIMING: loading files: 11.278 Hz, 0.089 s/exec, 1 execs, 0.089 s
"
"Flow builder exited with exit code 1; For details see debugging output"
Flow building error:  "Flow builder exited with exit code 1; For details see debugging output"
Failed creating optical flow, falling back to OpenCV ...
Failed attempts so far:  1
Building flow for left frame  0  to right frame  1 ; Size:  Original frame size
will try to use  "/tmp/cache/oFlowOrig/ocv-backward-4294967295-0.sVflow"  as initial flow
calcOpticalFlowFarneback

**Comment by quindo** [comment]
I have not done anything specific with Xserver.  Is it a requirement?

**Comment by valgit** [comment]
well, not really a "requirement", but slowmovideo is using QT for it's graphical interface, and under Linux QT is using X11 ;-) so under Linux you need to have a X11 display to run slowmovideo !
