### ISSUE TITLE
Flow method setting not saving

### ISSUE THREAD

**Issue by sigrokBlack** [slowmoVideo/slowmoVideo#95]
Hi,
when trying to change the flow methode from CPU to external, the setting is not saved and not applied to the current project.
I'm using a GTX750Ti, Ubuntu 16.04. I couldn't spot there the config file is saved.
The setting always switches to CPU after pressing ok and reopening the preferences menu

**Comment by valgit** [comment]
can you post the console logs ?

**Comment by Green-Sky** [comment]
i kind of have the same "error"
log:
`.....
method is :  "V3D"
OpenCV Error: Unknown error code -6 (OpenCL function is not available: [clGetPlatformIDs]) in opencl_check_fn, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/ocl/src/cl_runtime/cl_runtime.cpp, line 83
Checking  "/usr/bin/slowmoFlowBuilder"  ...
"/usr/bin/slowmoFlowBuilder"  is valid.
Checking  "/usr/bin/slowmoFlowBuilder"  ...
"/usr/bin/slowmoFlowBuilder"  is valid.
Checking  "/usr/bin/slowmoFlowBuilder"  ...
"/usr/bin/slowmoFlowBuilder"  is valid.
saving method  :  "V3D"
method is :  "V3D"
Checking  "/usr/bin/slowmoFlowBuilder"  ...
"/usr/bin/slowmoFlowBuilder"  is valid.
Checking  "/usr/bin/slowmoFlowBuilder"  ...
"/usr/bin/slowmoFlowBuilder"  is valid.
Checking  "/usr/bin/slowmoFlowBuilder"  ...
"/usr/bin/slowmoFlowBuilder"  is valid.
saving method  :  "OpenCV-Farnback"
check GPU
CUDA support :  0 found
OpenCL support
end OpenCL support
using Optical Flow Algo :  0
initial OpenCV setup`

**Comment by Green-Sky** [comment]
some how fixed it by installing the cuda-toolkit

**Comment by valgit** [comment]
@Green-Sky forum what I see in your log, there is a bug when you choose an "external method" but the check for available method fail ! I will try to take a look at what is going on there !

**Comment by grota** [comment]
I this my #107 can fix this

**Comment by valgit** [comment]
great @grota  thanks for closing
