### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by iqqmuT** [slowmoVideo/slowmoVideo#99]
Would it be a good idea to build a snap package for slowmoVideo?

**Comment by valgit** [comment]
what is a "snap" package ?

**Comment by iqqmuT** [comment]
Sorry I didn't explain it better, a snap is a new universal package format for different Linux distributions. They were introduced to Ubuntu in 16.04 version.

AFAIK dependencies are bundled within the snap package, so I guess it would be easier to maintain, for example the snap package would contain the correct Qt libraries.

http://snapcraft.io/

**Comment by Granjow** [comment]
@iqqmuT slowmoVideo is now available as AppImage. I will close this issue as it should be just as good as Snap (correct me if I am wrong) :)
